export default async function seedQuizQuestions(db) {
  const questions = [
    { id: 1, stage_code: 'R1', material_code: 'L1_C1', question_text: 'Huruf vokal Korea untuk bunyi a adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 1 },
    { id: 2, stage_code: 'R1', material_code: 'L1_C1', question_text: 'Huruf ㅑ dibaca ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 2 },
    { id: 3, stage_code: 'R1', material_code: 'L1_C1', question_text: 'Huruf vokal Korea untuk bunyi eo adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 3 },
    { id: 4, stage_code: 'R1', material_code: 'L1_C1', question_text: 'Huruf ㅕ dibaca ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 4 },
    { id: 5, stage_code: 'R1', material_code: 'L1_C1', question_text: 'Huruf vokal Korea untuk bunyi o adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 5 },
    { id: 6, stage_code: 'R1', material_code: 'L1_C1', question_text: 'Huruf ㅛ dibaca ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 6 },
    { id: 7, stage_code: 'R1', material_code: 'L1_C1', question_text: 'Huruf vokal Korea untuk bunyi u adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 7 },
    { id: 8, stage_code: 'R1', material_code: 'L1_C1', question_text: 'Huruf ㅠ dibaca ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 8 },
    { id: 9, stage_code: 'R1', material_code: 'L1_C1', question_text: 'Huruf vokal Korea untuk bunyi eu adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 9 },
    { id: 10, stage_code: 'R1', material_code: 'L1_C1', question_text: 'Huruf ㅣ dibaca ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 10 },
    { id: 11, stage_code: 'R1', material_code: 'L1_C2', question_text: 'Huruf ㅐ dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 11 },
    { id: 12, stage_code: 'R1', material_code: 'L1_C2', question_text: 'Huruf ㅒ dibaca ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 12 },
    { id: 13, stage_code: 'R1', material_code: 'L1_C2', question_text: 'Huruf ㅔ dibaca ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 13 },
    { id: 14, stage_code: 'R1', material_code: 'L1_C2', question_text: 'Huruf ㅖ dibaca ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 14 },
    { id: 15, stage_code: 'R1', material_code: 'L1_C2', question_text: 'Gabungan ㅡ + ㅣ membentuk huruf ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 15 },
    { id: 16, stage_code: 'R1', material_code: 'L1_C2', question_text: 'Huruf ㅘ dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 16 },
    { id: 17, stage_code: 'R1', material_code: 'L1_C2', question_text: 'Huruf ㅝ dibaca ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 17 },
    { id: 18, stage_code: 'R1', material_code: 'L1_C2', question_text: 'Huruf ㅟ dibaca ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 18 },
    { id: 19, stage_code: 'R1', material_code: 'L1_C2', question_text: 'Huruf ㅚ dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 19 },
    { id: 20, stage_code: 'R1', material_code: 'L1_C2', question_text: 'Huruf ㅙ dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 20 },
    { id: 21, stage_code: 'R1', material_code: 'L1_C3', question_text: 'Huruf ㄱ dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 21 },
    { id: 22, stage_code: 'R1', material_code: 'L1_C3', question_text: 'Huruf ㄴ dibaca ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 22 },
    { id: 23, stage_code: 'R1', material_code: 'L1_C3', question_text: 'Huruf ㄷ dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 23 },
    { id: 24, stage_code: 'R1', material_code: 'L1_C3', question_text: 'Huruf ㄹ dibaca ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 24 },
    { id: 25, stage_code: 'R1', material_code: 'L1_C3', question_text: 'Huruf ㅁ dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 25 },
    { id: 26, stage_code: 'R1', material_code: 'L1_C3', question_text: 'Huruf ㅂ dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 26 },
    { id: 27, stage_code: 'R1', material_code: 'L1_C3', question_text: 'Huruf ㅅ dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 27 },
    { id: 28, stage_code: 'R1', material_code: 'L1_C3', question_text: 'Huruf ㅇ berfungsi sebagai ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 28 },
    { id: 29, stage_code: 'R1', material_code: 'L1_C4', question_text: 'Kata 가 dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 29 },
    { id: 30, stage_code: 'R1', material_code: 'L1_C4', question_text: 'Kata 사 dibaca ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 30 },
    { id: 31, stage_code: 'R2', material_code: 'L1_C5', question_text: 'Saat membaca papan informasi di bandara Korea, huruf ㄲ dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 1 },
    { id: 32, stage_code: 'R2', material_code: 'L1_C5', question_text: 'Huruf ㄸ dalam tulisan Korea dibaca ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 2 },
    { id: 33, stage_code: 'R2', material_code: 'L1_C5', question_text: 'Huruf ㅃ dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 3 },
    { id: 34, stage_code: 'R2', material_code: 'L1_C5', question_text: 'Huruf ㅆ dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 4 },
    { id: 35, stage_code: 'R2', material_code: 'L1_C5', question_text: 'Huruf ㅉ dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 5 },
    { id: 36, stage_code: 'R2', material_code: 'L1_C5', question_text: 'Saat membaca tulisan Korea di papan restoran, huruf ㅆ pada kata 씨 menunjukkan bunyi yang ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 6 },
    { id: 37, stage_code: 'R2', material_code: 'L1_C6', question_text: 'Saat melihat kata 끼 di menu makanan Korea, cara bacanya adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 7 },
    { id: 38, stage_code: 'R2', material_code: 'L1_C6', question_text: 'Kata 따 dibaca ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 8 },
    { id: 39, stage_code: 'R2', material_code: 'L1_C6', question_text: 'Kata 빠 dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 9 },
    { id: 40, stage_code: 'R2', material_code: 'L1_C6', question_text: 'Kata 씨 dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 10 },
    { id: 41, stage_code: 'R2', material_code: 'L1_C6', question_text: 'Kata 짜 dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 11 },
    { id: 42, stage_code: 'R2', material_code: 'L1_C7', question_text: 'Dalam batchim dasar, ㄱ/ㅋ/ㄲ dibaca sebagai ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 12 },
    { id: 43, stage_code: 'R2', material_code: 'L1_C7', question_text: 'Dalam batchim dasar, ㄴ dibaca sebagai ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 13 },
    { id: 44, stage_code: 'R2', material_code: 'L1_C7', question_text: 'Dalam batchim dasar, ㄷ/ㅌ/ㅅ/ㅈ/ㅊ/ㅎ dibaca sebagai ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 14 },
    { id: 45, stage_code: 'R2', material_code: 'L1_C7', question_text: 'Dalam batchim dasar, ㄹ dibaca sebagai ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 15 },
    { id: 46, stage_code: 'R2', material_code: 'L1_C7', question_text: 'Dalam batchim dasar, ㅁ dibaca sebagai ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 16 },
    { id: 47, stage_code: 'R2', material_code: 'L1_C7', question_text: 'Dalam batchim dasar, ㅂ/ㅍ dibaca sebagai ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 17 },
    { id: 48, stage_code: 'R2', material_code: 'L1_C7', question_text: 'Dalam batchim dasar, ㅇ dibaca sebagai ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 18 },
    { id: 49, stage_code: 'R2', material_code: 'L1_C8', question_text: 'Saat membaca nama tempat/label di Korea, kata 각 dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 19 },
    { id: 50, material_code: 'L1_C8', question_text: 'Kata 안 dibaca ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 20, stage_code: 'R2' },
    { id: 51, stage_code: 'R2', material_code: 'L1_C8', question_text: 'Kata 닫 dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 21 },
    { id: 52, stage_code: 'R2', material_code: 'L1_C8', question_text: 'Kata 갈 dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 22 },
    { id: 53, stage_code: 'R2', material_code: 'L1_C8', question_text: 'Kata 삼 dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 23 },
    { id: 54, stage_code: 'R2', material_code: 'L1_C8', question_text: 'Kata 밥 dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 24 },
    { id: 55, stage_code: 'R2', material_code: 'L1_C8', question_text: 'Kata 영 dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 25 },
    { id: 56, stage_code: 'R2', material_code: 'L1_C9', question_text: 'Pada contoh batchim ganda, kata 삯 dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 26 },
    { id: 57, stage_code: 'R2', material_code: 'L1_C9', question_text: 'Kata 많ta dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 27 },
    { id: 58, stage_code: 'R2', material_code: 'L1_C9', question_text: 'Kata 없다 dibaca ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 28 },
    { id: 59, stage_code: 'R2', material_code: 'L1_C10', question_text: 'Dalam konteks traveling, saat membaca frasa 없음 → 없어, bunyi berubah menjadi ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 29 },
    { id: 60, stage_code: 'R2', material_code: 'L1_C10', question_text: 'Saat membaca frasa 먹어요, cara bacanya adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 30 },
    { id: 61, stage_code: 'R3', material_code: 'L2_C1', question_text: 'Kalimat 이름이 뭐예요? (i-reum-i mwo-ye-yo?) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 1 },
    { id: 62, stage_code: 'R3', material_code: 'L2_C1', question_text: 'Arti kata 이름 (i-reum) adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 2 },
    { id: 63, stage_code: 'R3', material_code: 'L2_C1', question_text: 'Kalimat yang tepat untuk mengatakan “Nama saya Jessica” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 3 },
    { id: 64, stage_code: 'R3', material_code: 'L2_C1', question_text: '제 이름은 Jessica예요 (je i-reum-eun Jessica-ye-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 4 },
    { id: 65, stage_code: 'R3', material_code: 'L2_C1', question_text: 'Untuk menanyakan nama seseorang, kalimat yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 5 },
    { id: 66, stage_code: 'R3', material_code: 'L2_C1', question_text: 'Dalam kalimat 제 이름은 Jessica예요 (je i-reum-eun Jessica-ye-yo), kata 이름 (i-reum) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 6 },
    { id: 67, stage_code: 'R3', material_code: 'L2_C2', question_text: '이에요/예요 (i-e-yo/ye-yo) memiliki arti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 7 },
    { id: 68, stage_code: 'R3', material_code: 'L2_C2', question_text: 'Setelah kata benda berakhiran konsonan, bentuk yang digunakan adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 8 },
    { id: 69, stage_code: 'R3', material_code: 'L2_C2', question_text: 'Setelah kata benda berakhiran vokal, bentuk yang digunakan adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 9 },
    { id: 70, stage_code: 'R3', material_code: 'L2_C2', question_text: 'Kalimat yang berarti “Ini paspor” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 10 },
    { id: 71, stage_code: 'R3', material_code: 'L2_C2', question_text: '가방이에요 (ga-bang-i-e-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 11 },
    { id: 72, stage_code: 'R3', material_code: 'L2_C2', question_text: '카메라예요 (ka-me-ra-ye-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 12 },
    { id: 73, stage_code: 'R3', material_code: 'L2_C2', question_text: 'Kata 여권 (yeo-gwon) memakai 이에요 (i-e-yo) karena ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 13 },
    { id: 74, stage_code: 'R3', material_code: 'L2_C2', question_text: 'Kata 카메라 (ka-me-ra) memakai 예요 (ye-yo) karena ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 14 },
    { id: 75, stage_code: 'R3', material_code: 'L2_C2', question_text: 'Pilihan yang benar untuk “Ini tas” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 15 },
    { id: 76, stage_code: 'R3', material_code: 'L2_C3', question_text: '이게 뭐예요? (i-ge mwo-ye-yo?) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 16 },
    { id: 77, stage_code: 'R3', material_code: 'L2_C3', question_text: 'Jawaban yang tepat untuk pertanyaan “Ini apa?” jika bendanya tas adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 17 },
    { id: 78, stage_code: 'R3', material_code: 'L2_C3', question_text: 'Jawaban yang tepat untuk pertanyaan “Ini apa?” jika bendanya paspor adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 18 },
    { id: 79, stage_code: 'R3', material_code: 'L2_C3', question_text: 'Jawaban yang tepat untuk pertanyaan “Ini apa?” jika bendanya kamera adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 19 },
    { id: 80, stage_code: 'R3', material_code: 'L2_C3', question_text: 'Jawaban yang tepat untuk pertanyaan “Ini apa?” jika bendanya kacamata hitam adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 20 },
    { id: 81, stage_code: 'R3', material_code: 'L2_C3', question_text: 'Pilih pasangan tanya-jawab yang benar.', question_type: 'multiple_choice', correct_answer: 'A', question_order: 21 },
    { id: 82, stage_code: 'R3', material_code: 'L2_C3', question_text: 'Pertanyaan yang tepat untuk menanyakan “Ini apa?” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 22 },
    { id: 83, stage_code: 'R3', material_code: 'L2_C4', question_text: 'Partikel 은/는 (eun/neun) berfungsi sebagai ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 23 },
    { id: 84, stage_code: 'R3', material_code: 'L2_C4', question_text: 'Setelah kata berakhiran konsonan, partikel topik yang digunakan adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 24 },
    { id: 85, stage_code: 'R3', material_code: 'L2_C4', question_text: 'Setelah kata berakhiran vokal, partikel topik yang digunakan adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 25 },
    { id: 86, stage_code: 'R3', material_code: 'L2_C4', question_text: '저는 학생이에요 (jeo-neun hak-saeng-i-e-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 26 },
    { id: 87, stage_code: 'R3', material_code: 'L2_C4', question_text: 'Dalam kalimat 저는 학생이에요 (jeo-neun hak-saeng-i-e-yo), partikel topiknya adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 27 },
    { id: 88, stage_code: 'R3', material_code: 'L2_C4', question_text: '정한은 가수예요 (jeong-han-eun ga-su-ye-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 28 },
    { id: 89, stage_code: 'R3', material_code: 'L2_C4', question_text: 'Mengapa 정한 (jeong-han) menggunakan partikel 은 (eun)?', question_type: 'multiple_choice', correct_answer: 'A', question_order: 29 },
    { id: 90, stage_code: 'R3', material_code: 'L2_C4', question_text: 'Pilih kalimat yang benar menggunakan partikel topik.', question_type: 'multiple_choice', correct_answer: 'A', question_order: 30 },
    { id: 91, stage_code: 'R4', material_code: 'L2_C5', question_text: '안녕하세요 (an-nyeong-ha-se-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 1 },
    { id: 92, stage_code: 'R4', material_code: 'L2_C5', question_text: 'Sapaan formal untuk mengatakan “Halo” adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 2 },
    { id: 93, stage_code: 'R4', material_code: 'L2_C5', question_text: '감사합니다 (gam-sa-ham-ni-da) berarti ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 3 },
    { id: 94, stage_code: 'R4', material_code: 'L2_C5', question_text: 'Ungkapan untuk mengatakan “Terima kasih” adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 4 },
    { id: 95, stage_code: 'R4', material_code: 'L2_C5', question_text: '고마워요 (go-ma-wo-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 5 },
    { id: 96, stage_code: 'R4', material_code: 'L2_C5', question_text: 'Ungkapan untuk mengatakan “Maaf” secara sopan adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 6 },
    { id: 97, stage_code: 'R4', material_code: 'L2_C5', question_text: '죄송합니다 (joe-song-ham-ni-da) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 7 },
    { id: 98, stage_code: 'R4', material_code: 'L2_C5', question_text: 'Saat ingin mengatakan “Selamat jalan”, ungkapan yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 8 },
    { id: 99, stage_code: 'R4', material_code: 'L2_C5', question_text: '안녕히 계세요 (an-nyeong-hi gye-se-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 9 },
    { id: 100, stage_code: 'R4', material_code: 'L2_C5', question_text: '반가워요 (man-na-seo ban-ga-wo-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 10 },
    { id: 101, stage_code: 'R4', material_code: 'L2_C6', question_text: '여권 (yeo-gwon) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 11 },
    { id: 102, stage_code: 'R4', material_code: 'L2_C6', question_text: 'Kata Korea untuk “paspor” adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 12 },
    { id: 103, stage_code: 'R4', material_code: 'L2_C6', question_text: '케리어 (ke-ri-eo) berarti ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 13 },
    { id: 104, stage_code: 'R4', material_code: 'L2_C6', question_text: 'Kata Korea untuk “koper” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 14 },
    { id: 105, stage_code: 'R4', material_code: 'L2_C6', question_text: '카메라 (ka-me-ra) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 15 },
    { id: 106, stage_code: 'R4', material_code: 'L2_C6', question_text: 'Kata Korea untuk “tas” adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 16 },
    { id: 107, stage_code: 'R4', material_code: 'L2_C6', question_text: '비행기표 (bi-haeng-gi-pyo) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 17 },
    { id: 108, stage_code: 'R4', material_code: 'L2_C6', question_text: 'Kata Korea untuk “pesawat” adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 18 },
    { id: 109, stage_code: 'R4', material_code: 'L2_C6', question_text: '공항 (gong-hang) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 19 },
    { id: 110, stage_code: 'R4', material_code: 'L2_C6', question_text: 'Kata Korea untuk “kacamata hitam” adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 20 },
    { id: 111, stage_code: 'R4', material_code: 'L2_C7', question_text: '가수 (ga-su) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 21 },
    { id: 112, stage_code: 'R4', material_code: 'L2_C7', question_text: 'Kata Korea untuk “aktor” adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 22 },
    { id: 113, stage_code: 'R4', material_code: 'L2_C7', question_text: '학생 (hak-saeng) berarti ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 23 },
    { id: 114, stage_code: 'R4', material_code: 'L2_C7', question_text: 'Kata Korea untuk “polisi” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 24 },
    { id: 115, stage_code: 'R4', material_code: 'L2_C7', question_text: '의사 (ui-sa) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 25 },
    { id: 116, stage_code: 'R4', material_code: 'L2_C7', question_text: 'Kata Korea untuk “guru” adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 26 },
    { id: 117, stage_code: 'R4', material_code: 'L2_C7', question_text: '간호사 (gan-ho-sa) berarti ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 27 },
    { id: 118, stage_code: 'R4', material_code: 'L2_C7', question_text: 'Kata Korea untuk “koki” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 28 },
    { id: 119, stage_code: 'R4', material_code: 'L2_C7', question_text: '회사원 (hoe-sa-won) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 29 },
    { id: 120, stage_code: 'R4', material_code: 'L2_C7', question_text: 'Kata Korea untuk “pegawai bank” adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 30 },
    { id: 121, stage_code: 'U1', material_code: 'L3_C1', question_text: '실례하지만 (sil-lye-ha-ji-man) digunakan saat ingin ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 1 },
    { id: 122, stage_code: 'U1', material_code: 'L3_C1', question_text: 'Ungkapan yang tepat untuk mengatakan “Permisi” adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 2 },
    { id: 123, stage_code: 'U1', material_code: 'L3_C1', question_text: '물어봐도 돼요? (mu-reo-bwa-do dwae-yo?) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 3 },
    { id: 124, stage_code: 'U1', material_code: 'L3_C1', question_text: 'Saat ingin bertanya dengan sopan kepada orang di Korea, kalimat yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 4 },
    { id: 125, stage_code: 'U1', material_code: 'L3_C1', question_text: '네, 말씀하세요 (ne, mal-sseum-ha-se-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 5 },
    { id: 126, stage_code: 'U1', material_code: 'L3_C1', question_text: 'Respon yang tepat setelah seseorang bertanya dengan sopan adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 6 },
    { id: 127, stage_code: 'U1', material_code: 'L3_C1', question_text: '여기 어디예요? (yeo-gi neun eo-di-ye-yo?) digunakan untuk menanyakan ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 7 },
    { id: 128, stage_code: 'U1', material_code: 'L3_C1', question_text: 'Kalimat yang berarti “Ini tempat apa?” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 8 },
    { id: 129, stage_code: 'U1', material_code: 'L3_C1', question_text: '여기는 경복궁이에요 (yeo-gi-neun gyeong-bok-gung-i-e-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 9 },
    { id: 130, stage_code: 'U1', material_code: 'L3_C1', question_text: 'Jika seseorang bertanya 여기 어디예요? (yeo-gi neun eo-di-ye-yo?), jawaban yang sesuai adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 10 },
    { id: 131, stage_code: 'U1', material_code: 'L3_C1', question_text: 'Urutan percakapan yang paling masuk akal adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 11 },
    { id: 132, stage_code: 'U1', material_code: 'L3_C1', question_text: 'Dalam situasi traveling, sebelum bertanya kepada orang asing, ungkapan paling sopan adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 12 },
    { id: 133, stage_code: 'U1', material_code: 'L3_C1', question_text: 'Pertanyaan 물어봐도 돼요? (mu-reo-bwa-do dwae-yo?) paling cocok dijawab dengan ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 13 },
    { id: 134, stage_code: 'U1', material_code: 'L3_C1', question_text: 'Jika ingin mengetahui lokasi saat berada di tempat wisata, kalimat yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 14 },
    { id: 135, stage_code: 'U1', material_code: 'L3_C1', question_text: 'Kalimat 여기는 경복궁이에요 (yeo-gi-neun gyeong-bok-gung-i-e-yo) paling tepat digunakan untuk ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 15 },
    { id: 136, stage_code: 'U1', material_code: 'L3_C2', question_text: '이 (i) digunakan untuk benda yang ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 16 },
    { id: 137, stage_code: 'U1', material_code: 'L3_C2', question_text: '그 (geu) digunakan untuk benda yang ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 17 },
    { id: 138, stage_code: 'U1', material_code: 'L3_C2', question_text: '저 (jeo) digunakan untuk benda yang ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 18 },
    { id: 139, stage_code: 'U1', material_code: 'L3_C2', question_text: '이 가방 (i ga-bang) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 19 },
    { id: 140, stage_code: 'U1', material_code: 'L3_C2', question_text: 'Jika tas berada dekat pembicara, bentuk yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 20 },
    { id: 141, stage_code: 'U1', material_code: 'L3_C2', question_text: '그 카메라 (geu ka-me-ra) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 21 },
    { id: 142, stage_code: 'U1', material_code: 'L3_C2', question_text: 'Jika kamera berada dekat pendengar, bentuk yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 22 },
    { id: 143, stage_code: 'U1', material_code: 'L3_C2', question_text: '저 비행기 (jeo bi-haeng-gi) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 23 },
    { id: 144, stage_code: 'U1', material_code: 'L3_C2', question_text: 'Jika pesawat berada jauh dari pembicara dan pendengar, bentuk yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 24 },
    { id: 145, stage_code: 'U1', material_code: 'L3_C2', question_text: 'Pasangan arti yang benar adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 25 },
    { id: 146, stage_code: 'U1', material_code: 'L3_C2', question_text: 'Dalam frasa 이 가방 (i ga-bang), kata 이 (i) menunjukkan ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 26 },
    { id: 147, stage_code: 'U1', material_code: 'L3_C2', question_text: 'Dalam frasa 그 카메라 (geu ka-me-ra), kata 그 (geu) menunjukkan ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 27 },
    { id: 148, stage_code: 'U1', material_code: 'L3_C2', question_text: 'Dalam frasa 저 비행기 (jeo bi-haeng-gi), kata 저 (jeo) menunjukkan ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 28 },
    { id: 149, stage_code: 'U1', material_code: 'L3_C2', question_text: 'Pilih frasa yang berarti “tas ini”.', question_type: 'multiple_choice', correct_answer: 'B', question_order: 29 },
    { id: 150, stage_code: 'U1', material_code: 'L3_C2', question_text: 'Pilih frasa yang berarti “pesawat itu jauh”.', question_type: 'multiple_choice', correct_answer: 'C', question_order: 30 },
    { id: 151, stage_code: 'U2', material_code: 'L3_C3', question_text: '여기 (yeo-gi) digunakan untuk menunjukkan tempat yang ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 1 },
    { id: 152, stage_code: 'U2', material_code: 'L3_C3', question_text: '거기 (geo-gi) digunakan untuk menunjukkan tempat yang ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 2 },
    { id: 153, stage_code: 'U2', material_code: 'L3_C3', question_text: '저기 (jeo-gi) digunakan untuk menunjukkan tempat yang ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 3 },
    { id: 154, stage_code: 'U2', material_code: 'L3_C3', question_text: 'Kata Korea untuk “di sini” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 4 },
    { id: 155, stage_code: 'U2', material_code: 'L3_C3', question_text: 'Kata Korea untuk “di situ” adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 5 },
    { id: 156, stage_code: 'U2', material_code: 'L3_C3', question_text: 'Kata Korea untuk “di sana” adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 6 },
    { id: 157, stage_code: 'U2', material_code: 'L3_C3', question_text: '여기는 어디예요? (yeo-gi-neun eo-di-ye-yo?) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 7 },
    { id: 158, stage_code: 'U2', material_code: 'L3_C3', question_text: 'Saat ingin bertanya “Ini tempat apa?”, kalimat yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 8 },
    { id: 159, stage_code: 'U2', material_code: 'L3_C3', question_text: 'Jika tempatnya dekat pembicara, bentuk yang paling tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 9 },
    { id: 160, stage_code: 'U2', material_code: 'L3_C3', question_text: 'Jika tempatnya dekat pendengar, kata yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 10 },
    { id: 161, stage_code: 'U2', material_code: 'L3_C3', question_text: 'Jika tempatnya jauh dari pembicara dan pendengar, kata yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 11 },
    { id: 162, stage_code: 'U2', material_code: 'L3_C3', question_text: 'Dalam kalimat 여기는 어디예요? (yeo-gi-neun eo-di-ye-yo?), kata 어디 (eo-di) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 12 },
    { id: 163, stage_code: 'U2', material_code: 'L3_C3', question_text: 'Pasangan arti yang benar adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 13 },
    { id: 164, stage_code: 'U2', material_code: 'L3_C3', question_text: 'Pasangan yang benar adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 14 },
    { id: 165, stage_code: 'U2', material_code: 'L3_C3', question_text: 'Kalimat 거기는 어디예요? (geo-gi-neun eo-di-ye-yo?) paling tepat digunakan jika bertanya tentang tempat yang ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 15 },
    { id: 166, stage_code: 'U2', material_code: 'L3_C4', question_text: '이쪽 (i-jjok) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 16 },
    { id: 167, stage_code: 'U2', material_code: 'L3_C4', question_text: '그쪽 (geu-jjok) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 17 },
    { id: 168, stage_code: 'U2', material_code: 'L3_C4', question_text: '저쪽 (jeo-jjok) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 18 },
    { id: 169, stage_code: 'U2', material_code: 'L3_C4', question_text: 'Kata Korea untuk “arah sini” adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 19 },
    { id: 170, stage_code: 'U2', material_code: 'L3_C4', question_text: 'Kata Korea untuk “arah situ” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 20 },
    { id: 171, stage_code: 'U2', material_code: 'L3_C4', question_text: 'Kata Korea untuk “arah sana” adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 21 },
    { id: 172, stage_code: 'U2', material_code: 'L3_C4', question_text: '화장실이 어디예요? (hwa-jang-sil-i eo-di-ye-yo?) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 22 },
    { id: 173, stage_code: 'U2', material_code: 'L3_C4', question_text: '저쪽이에요 (jeo-jjok-i-e-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 23 },
    { id: 174, stage_code: 'U2', material_code: 'L3_C4', question_text: 'Jika seseorang bertanya 화장실이 어디예요? (hwa-jang-sil-i eo-di-ye-yo?), jawaban yang sesuai dari chunk adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 24 },
    { id: 175, stage_code: 'U2', material_code: 'L3_C4', question_text: 'Saat menjelaskan toilet berada di arah sana, kalimat yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 25 },
    { id: 176, stage_code: 'U2', material_code: 'L3_C4', question_text: 'Dalam 화장실이 어디예요? (hwa-jang-sil-i eo-di-ye-yo?), kata 화장실 (hwa-jang-sil) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 26 },
    { id: 177, stage_code: 'U2', material_code: 'L3_C4', question_text: 'Pola 쪽 (jjok) digunakan untuk menyatakan ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 27 },
    { id: 178, stage_code: 'U2', material_code: 'L3_C4', question_text: 'Pasangan arti yang benar adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 28 },
    { id: 179, stage_code: 'U2', material_code: 'L3_C4', question_text: 'Jika arah yang dimaksud dekat pembicara, bentuk yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 29 },
    { id: 180, stage_code: 'U2', material_code: 'L3_C4', question_text: 'Urutan percakapan yang paling masuk akal adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 30 },
    { id: 181, stage_code: 'U3', material_code: 'L3_C5', question_text: '-에 가요 (-e ga-yo) digunakan untuk menyatakan ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 1 },
    { id: 182, stage_code: 'U3', material_code: 'L3_C5', question_text: '어디 가요? (eo-di ga-yo?) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 2 },
    { id: 183, stage_code: 'U3', material_code: 'L3_C5', question_text: 'Kalimat yang berarti “Pergi ke mana?” adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 3 },
    { id: 184, stage_code: 'U3', material_code: 'L3_C5', question_text: '편의점에 가요 (pyeon-ui-jeom-e ga-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 4 },
    { id: 185, stage_code: 'U3', material_code: 'L3_C5', question_text: 'Jawaban yang tepat untuk pertanyaan 어디 가요? (eo-di ga-yo?) adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 5 },
    { id: 186, stage_code: 'U3', material_code: 'L3_C5', question_text: 'Jika ingin mengatakan “pergi ke minimarket”, kalimat yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 6 },
    { id: 187, stage_code: 'U3', material_code: 'L3_C5', question_text: 'Dalam 편의점에 가요 (pyeon-ui-jeom-e ga-yo), bagian 에 가요 (-e ga-yo) menunjukkan ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 7 },
    { id: 188, stage_code: 'U3', material_code: 'L3_C5', question_text: 'Dalam konteks traveling, pola -에 가요 (-e ga-yo) cocok dipakai saat menjelaskan ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 8 },
    { id: 189, stage_code: 'U3', material_code: 'L3_C5', question_text: 'Pilih pasangan tanya-jawab yang benar.', question_type: 'multiple_choice', correct_answer: 'A', question_order: 9 },
    { id: 190, stage_code: 'U3', material_code: 'L3_C5', question_text: 'Kalimat 어디 가요? (eo-di ga-yo?) paling tepat digunakan untuk bertanya tentang ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 10 },
    { id: 191, stage_code: 'U3', material_code: 'L3_C5', question_text: 'Jika seseorang menjawab 편의점에 가요 (pyeon-ui-jeom-e ga-yo), pertanyaan yang paling sesuai adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 11 },
    { id: 192, stage_code: 'U3', material_code: 'L3_C5', question_text: 'Arti kata 어디 (eo-di) dalam 어디 가요? (eo-di ga-yo?) adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 12 },
    { id: 193, stage_code: 'U3', material_code: 'L3_C5', question_text: '가요 (ga-yo) dalam pola ini berhubungan dengan aktivitas ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 13 },
    { id: 194, stage_code: 'U3', material_code: 'L3_C5', question_text: 'Kalimat yang memakai pola tempat tujuan adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 14 },
    { id: 195, stage_code: 'U3', material_code: 'L3_C5', question_text: 'Makna utama dari kalimat 편의점에 가요 (pyeon-ui-jeom-e ga-yo) adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 15 },
    { id: 196, stage_code: 'U3', material_code: 'L4_C1', question_text: '-에 있어요 (-e i-sseo-yo) digunakan untuk menyatakan ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 16 },
    { id: 197, stage_code: 'U3', material_code: 'L4_C1', question_text: '가방i 어디에 있어요? (ga-bang-i eo-di-e i-sseo-yo?) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 17 },
    { id: 198, stage_code: 'U3', material_code: 'L4_C1', question_text: 'Kalimat yang berarti “Tas ada di mana?” adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 18 },
    { id: 199, stage_code: 'U3', material_code: 'L4_C1', question_text: '가방i 책상 앞에 있어요 (ga-bang-i chaek-sang ap-e i-sseo-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 19 },
    { id: 200, stage_code: 'U3', material_code: 'L4_C1', question_text: 'Jawaban yang tepat untuk 가방i 어디에 있어요? (ga-bang-i eo-di-e i-sseo-yo?) adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 20 },
    { id: 201, stage_code: 'U3', material_code: 'L4_C1', question_text: 'Dalam 가방이 책상 앞에 있어요 (ga-bang-i chaek-sang ap-e i-sseo-yo), kata 가방 (ga-bang) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 21 },
    { id: 202, stage_code: 'U3', material_code: 'L4_C1', question_text: 'Dalam 가방이 책상 앞에 있어요 (ga-bang-i chaek-sang ap-e i-sseo-yo), 책상 앞 (chaek-sang ap) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 22 },
    { id: 203, stage_code: 'U3', material_code: 'L4_C1', question_text: 'Pilih kalimat yang menunjukkan lokasi benda.', question_type: 'multiple_choice', correct_answer: 'C', question_order: 23 },
    { id: 204, stage_code: 'U3', material_code: 'L4_C1', question_text: 'Pola -에 있어요 (-e i-sseo-yo) cocok dipakai saat ingin menjelaskan ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 24 },
    { id: 205, stage_code: 'U3', material_code: 'L4_C1', question_text: 'Perbedaan utama -에 가요 (-e ga-yo) dan -에 있어요 (-e i-sseo-yo) adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 25 },
    { id: 206, stage_code: 'U3', material_code: 'L4_C1', question_text: 'Jika ingin bertanya letak tas, kalimat yang benar adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 26 },
    { id: 207, stage_code: 'U3', material_code: 'L4_C1', question_text: 'Jika ingin menjawab “Tas ada di depan meja”, kalimat yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 27 },
    { id: 208, stage_code: 'U3', material_code: 'L4_C1', question_text: '어디에 있어요? (eo-di-e i-sseo-yo?) digunakan untuk bertanya ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 28 },
    { id: 209, stage_code: 'U3', material_code: 'L4_C1', question_text: 'Pilih pasangan tanya-jawab yang benar.', question_type: 'multiple_choice', correct_answer: 'C', question_order: 29 },
    { id: 210, stage_code: 'U3', material_code: 'L4_C1', question_text: 'Urutan percakapan yang paling masuk akal adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 30 },
    { id: 211, stage_code: 'U4', material_code: 'L4_C2', question_text: '위 (wi) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 1 },
    { id: 212, stage_code: 'U4', material_code: 'L4_C2', question_text: 'Kata Korea untuk “di bawah” adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 2 },
    { id: 213, stage_code: 'U4', material_code: 'L4_C2', question_text: '앞 (ap) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 3 },
    { id: 214, stage_code: 'U4', material_code: 'L4_C2', question_text: 'Kata Korea untuk “di belakang” adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 4 },
    { id: 215, stage_code: 'U4', material_code: 'L4_C2', question_text: '옆 (yeop) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 5 },
    { id: 216, stage_code: 'U4', material_code: 'L4_C2', question_text: 'Kata Korea untuk “di antara” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 6 },
    { id: 217, stage_code: 'U4', material_code: 'L4_C2', question_text: '안 (an) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 7 },
    { id: 218, stage_code: 'U4', material_code: 'L4_C2', question_text: 'Kata Korea untuk “di luar” adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 8 },
    { id: 219, stage_code: 'U4', material_code: 'L4_C2', question_text: 'Pasangan arti yang benar adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 9 },
    { id: 220, stage_code: 'U4', material_code: 'L4_C2', question_text: 'Pasangan yang berlawanan makna adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 10 },
    { id: 221, stage_code: 'U4', material_code: 'L4_C2', question_text: 'Pasangan yang berarti “di dalam” dan “di luar” adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 11 },
    { id: 222, stage_code: 'U4', material_code: 'L4_C2', question_text: 'Jika ingin menyatakan posisi “di samping”, kata yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 12 },
    { id: 223, stage_code: 'U4', material_code: 'L4_C2', question_text: 'Jika ingin menyatakan posisi “di antara”, kata yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 13 },
    { id: 224, stage_code: 'U4', material_code: 'L4_C2', question_text: '뒤 (dwi) memiliki makna kebalikan dari ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 14 },
    { id: 225, stage_code: 'U4', material_code: 'L4_C2', question_text: '밖 (bak) memiliki makna kebalikan dari ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 15 },
    { id: 226, stage_code: 'U4', material_code: 'L4_C3', question_text: '어떻게 가요? (eo-tteo-ke ga-yo?) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 16 },
    { id: 227, stage_code: 'U4', material_code: 'L4_C3', question_text: 'Kalimat yang tepat untuk bertanya “Pergi ke sana naik apa?” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 17 },
    { id: 228, stage_code: 'U4', material_code: 'L4_C3', question_text: '경복궁에 어떻게 가요? (gyeong-bok-gung-e eo-tteo-ke ga-yo?) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 18 },
    { id: 229, stage_code: 'U4', material_code: 'L4_C3', question_text: 'Kalimat yang tepat untuk bertanya “Ke Gyeongbokgung naik apa?” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 19 },
    { id: 230, stage_code: 'U4', material_code: 'L4_C3', question_text: 'Dalam kalimat 어떻게 가요? (eo-tteo-ke ga-yo?), kata 어떻게 (eo-tteo-ke) berfungsi untuk menanyakan ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 20 },
    { id: 231, stage_code: 'U4', material_code: 'L4_C3', question_text: 'Dalam kalimat 어떻게 가요? (eo-tteo-ke ga-yo?), kata 가요 (ga-yo) berhubungan dengan aktivitas ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 21 },
    { id: 232, stage_code: 'U4', material_code: 'L4_C3', question_text: 'Pola 어떻게 가요? (eo-tteo-ke ga-yo?) paling tepat digunakan saat ingin bertanya tentang ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 22 },
    { id: 233, stage_code: 'U4', material_code: 'L4_C3', question_text: 'Jika tujuan yang ditanyakan adalah Gyeongbokgung, kalimat yang paling tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 23 },
    { id: 234, stage_code: 'U4', material_code: 'L4_C3', question_text: 'Bagian 경복궁에 (gyeong-bok-gung-e) dalam 경복궁에 어떻게 가요? (gyeong-bok-gung-e eo-tteo-ke ga-yo?) menunjukkan ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 24 },
    { id: 235, stage_code: 'U4', material_code: 'L4_C3', question_text: 'Perbedaan 어디 가요? (eo-di ga-yo?) dan 어떻게 가요? (eo-tteo-ke ga-yo?) adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 25 },
    { id: 236, stage_code: 'U4', material_code: 'L4_C3', question_text: 'Jika seseorang ingin tahu cara pergi ke suatu tempat saat traveling, pertanyaan yang paling sesuai adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 26 },
    { id: 237, stage_code: 'U4', material_code: 'L4_C3', question_text: 'Pilih pasangan arti yang benar.', question_type: 'multiple_choice', correct_answer: 'A', question_order: 27 },
    { id: 238, stage_code: 'U4', material_code: 'L4_C3', question_text: 'Kalimat 경복궁에 어떻게 가요? (gyeong-bok-gung-e eo-tteo-ke ga-yo?) cocok digunakan ketika ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 28 },
    { id: 239, stage_code: 'U4', material_code: 'L4_C3', question_text: 'Dalam konteks traveling, 어떻게 가요? (eo-tteo-ke ga-yo?) lebih fokus pada ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 29 },
    { id: 240, stage_code: 'U4', material_code: 'L4_C3', question_text: 'Pilih kalimat tanya transportasi yang benar.', question_type: 'multiple_choice', correct_answer: 'A', question_order: 30 },
    { id: 241, stage_code: 'U5', material_code: 'L4_C4', question_text: '지하철 (ji-ha-cheol) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 1 },
    { id: 242, stage_code: 'U5', material_code: 'L4_C4', question_text: 'Kata Korea untuk “bus” adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 2 },
    { id: 243, stage_code: 'U5', material_code: 'L4_C4', question_text: '택시 (taek-si) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 3 },
    { id: 244, stage_code: 'U5', material_code: 'L4_C4', question_text: 'Kata Korea untuk “kereta” adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 4 },
    { id: 245, stage_code: 'U5', material_code: 'L4_C4', question_text: '자동차 (ja-dong-cha) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 5 },
    { id: 246, stage_code: 'U5', material_code: 'L4_C4', question_text: 'Kata Korea untuk “sepeda” adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 6 },
    { id: 247, stage_code: 'U5', material_code: 'L4_C4', question_text: '비행기 (bi-haeng-gi) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 7 },
    { id: 248, stage_code: 'U5', material_code: 'L4_C4', question_text: 'Kata Korea untuk “kapal” adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 8 },
    { id: 249, stage_code: 'U5', material_code: 'L4_C4', question_text: 'Pasangan kosakata yang benar adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 9 },
    { id: 250, stage_code: 'U5', material_code: 'L4_C4', question_text: 'Pasangan yang termasuk transportasi darat adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 10 },
    { id: 251, stage_code: 'U5', material_code: 'L4_C4', question_text: 'Transportasi yang berarti “pesawat” dan “kapal” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 11 },
    { id: 252, stage_code: 'U5', material_code: 'L4_C4', question_text: 'Jika ingin menyebut “taksi” dalam bahasa Korea, pilih ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 12 },
    { id: 253, stage_code: 'U5', material_code: 'L4_C4', question_text: '기차 (gi-cha) berbeda dari 지하철 (ji-ha-cheol) karena 기차 berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 13 },
    { id: 254, stage_code: 'U5', material_code: 'L4_C4', question_text: 'Pilih arti yang benar untuk 자전거 (ja-jeon-geo).', question_type: 'multiple_choice', correct_answer: 'B', question_order: 14 },
    { id: 255, stage_code: 'U5', material_code: 'L4_C4', question_text: 'Pilih kosakata yang berarti “mobil”.', question_type: 'multiple_choice', correct_answer: 'C', question_order: 15 },
    { id: 256, stage_code: 'U5', material_code: 'L4_C5', question_text: 'Pola -(으)로 가요 (-(eu)ro ga-yo) digunakan untuk menyatakan ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 16 },
    { id: 257, stage_code: 'U5', material_code: 'L4_C5', question_text: '식당에 자전거로 가요 (sik-dang-e ja-jeon-geo-ro ga-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 17 },
    { id: 258, stage_code: 'U5', material_code: 'L4_C5', question_text: 'Kalimat yang berarti “Pergi ke restoran naik sepeda” adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 18 },
    { id: 259, stage_code: 'U5', material_code: 'L4_C5', question_text: 'Dalam 식당에 자전거로 가요 (sik-dang-e ja-jeon-geo-ro ga-yo), bagian 자전거로 (ja-jeon-geo-ro) menunjukkan ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 19 },
    { id: 260, stage_code: 'U5', material_code: 'L4_C5', question_text: 'Dalam pola -(으)로 가요 (-(eu)ro ga-yo), kata 가요 (ga-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 20 },
    { id: 261, stage_code: 'U5', material_code: 'L4_C5', question_text: 'Jika ingin mengatakan “pergi menggunakan bus”, bentuk yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 21 },
    { id: 262, stage_code: 'U5', material_code: 'L4_C5', question_text: 'Jika ingin mengatakan “pergi menggunakan taksi”, bentuk yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 22 },
    { id: 263, stage_code: 'U5', material_code: 'L4_C5', question_text: 'Jika ingin mengatakan “pergi menggunakan subway”, bentuk yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 23 },
    { id: 264, stage_code: 'U5', material_code: 'L4_C5', question_text: 'Jika ingin mengatakan “pergi menggunakan kapal”, bentuk yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 24 },
    { id: 265, stage_code: 'U5', material_code: 'L4_C5', question_text: 'Pilih pasangan arti yang benar.', question_type: 'multiple_choice', correct_answer: 'B', question_order: 25 },
    { id: 266, stage_code: 'U5', material_code: 'L4_C5', question_text: '자동차로 가요 (ja-dong-cha-ro ga-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 26 },
    { id: 267, stage_code: 'U5', material_code: 'L4_C5', question_text: '버스로 가요 (beo-seu-ro ga-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 27 },
    { id: 268, stage_code: 'U5', material_code: 'L4_C5', question_text: '비행기로 가요 (bi-haeng-gi-ro ga-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 28 },
    { id: 269, stage_code: 'U5', material_code: 'L4_C5', question_text: 'Pilih kalimat yang memakai pola “pergi menggunakan transportasi”.', question_type: 'multiple_choice', correct_answer: 'A', question_order: 29 },
    { id: 270, stage_code: 'U5', material_code: 'L4_C5', question_text: 'Jika pertanyaannya 어떻게 가요? (eo-tteo-ke ga-yo?), jawaban yang paling sesuai adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 30 },
    { id: 271, stage_code: 'A1', material_code: 'L5_C1', question_text: 'Saat di restoran, kamu ingin menyebut “nasi/makanan”. Kosakata yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 1 },
    { id: 272, stage_code: 'A1', material_code: 'L5_C1', question_text: 'Saat ingin membeli kopi di kafe, kata “kopi” dalam bahasa Korea adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 2 },
    { id: 273, stage_code: 'A1', material_code: 'L5_C1', question_text: 'Jika kamu mencari toilet saat traveling, kata yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 3 },
    { id: 274, stage_code: 'A1', material_code: 'L5_C1', question_text: 'Saat ingin menyebut “subway”, kosakata yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 4 },
    { id: 275, stage_code: 'A1', material_code: 'L5_C1', question_text: 'Saat berada di tempat belanja dan ingin menyebut “pakaian”, kata yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 5 },
    { id: 276, stage_code: 'A1', material_code: 'L5_C1', question_text: 'Jika kamu membawa “tas”, kosakata Korea yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 6 },
    { id: 277, stage_code: 'A1', material_code: 'L5_C1', question_text: 'Saat ingin menyebut “hotel”, pilih kosakata yang benar.', question_type: 'multiple_choice', correct_answer: 'C', question_order: 7 },
    { id: 278, stage_code: 'A1', material_code: 'L5_C1', question_text: 'Saat naik transportasi umum berupa “bus”, kata Korea yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 8 },
    { id: 279, stage_code: 'A1', material_code: 'L5_C1', question_text: 'Jika konteksnya tempat makan, kata yang paling tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 9 },
    { id: 280, stage_code: 'A1', material_code: 'L5_C1', question_text: 'Saat ingin menyebut “air/minuman”, kosakata yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 10 },
    { id: 281, stage_code: 'A1', material_code: 'L5_C2', question_text: 'Dalam pola objek, 을/를 (eul/reul) digunakan bersama ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 11 },
    { id: 282, stage_code: 'A1', material_code: 'L5_C2', question_text: 'Kalimat 뭘 먹어요? (mwol meo-geo-yo?) berarti ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 12 },
    { id: 283, stage_code: 'A1', material_code: 'L5_C2', question_text: 'Jika seseorang bertanya “Makan apa?”, kalimat Korea yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 13 },
    { id: 284, stage_code: 'A1', material_code: 'L5_C2', question_text: 'Kalimat 뭘 사요? (mwol sa-yo?) paling tepat digunakan saat ingin bertanya ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 14 },
    { id: 285, stage_code: 'A1', material_code: 'L5_C2', question_text: 'Jika ingin mengatakan “minum susu”, kalimat yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 15 },
    { id: 286, stage_code: 'A1', material_code: 'L5_C2', question_text: 'Kalimat 바나나우유를 마셔요 (ba-na-na-u-yu-reul ma-syeo-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 16 },
    { id: 287, stage_code: 'A1', material_code: 'L5_C2', question_text: 'Dalam 우유를 마셔요 (u-yu-reul ma-syeo-yo), partikel objeknya adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 17 },
    { id: 288, stage_code: 'A1', material_code: 'L5_C2', question_text: 'Jika kata benda diakhiri vokal seperti 우유 (u-yu), partikel objek yang dipakai adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 18 },
    { id: 289, stage_code: 'A1', material_code: 'L5_C2', question_text: 'Pilih pasangan tanya-jawab yang paling sesuai.', question_type: 'multiple_choice', correct_answer: 'C', question_order: 19 },
    { id: 290, stage_code: 'A1', material_code: 'L5_C2', question_text: 'Saat membeli minuman susu pisang, kalimat yang paling sesuai dari chunk adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 20 },
    { id: 291, stage_code: 'A1', material_code: 'L5_C3', question_text: 'Jika makanan terasa “enak”, kata sifat yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 21 },
    { id: 292, stage_code: 'A1', material_code: 'L5_C3', question_text: '비싸요 (bi-ssa-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 22 },
    { id: 293, stage_code: 'A1', material_code: 'L5_C3', question_text: 'Saat harga barang murah, kata sifat yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 23 },
    { id: 294, stage_code: 'A1', material_code: 'L5_C3', question_text: 'Jika hotel berada dekat, kata yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 24 },
    { id: 295, stage_code: 'A1', material_code: 'L5_C3', question_text: '멀어요 (meo-reo-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 25 },
    { id: 296, stage_code: 'A1', material_code: 'L5_C3', question_text: 'Jika toilet bersih, kalimat sifat yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 26 },
    { id: 297, stage_code: 'A1', material_code: 'L5_C3', question_text: 'Pasangan kata sifat yang berlawanan makna adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 27 },
    { id: 298, stage_code: 'A1', material_code: 'L5_C3', question_text: 'Jika ingin mengatakan “mahal”, pilih kata yang tepat.', question_type: 'multiple_choice', correct_answer: 'C', question_order: 28 },
    { id: 299, stage_code: 'A1', material_code: 'L5_C3', question_text: 'Saat restoran jauh dari hotel, kata sifat yang paling sesuai adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 29 },
    { id: 300, stage_code: 'A1', material_code: 'L5_C3', question_text: 'Saat menilai kafe bersih, kata sifat yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 30 },
    { id: 301, stage_code: 'A2', material_code: 'L5_C4', question_text: 'Saat ingin mengatakan “pergi”, kata kerja Korea yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 1 },
    { id: 302, stage_code: 'A2', material_code: 'L5_C4', question_text: '와요 (wa-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 2 },
    { id: 303, stage_code: 'A2', material_code: 'L5_C4', question_text: 'Saat ingin mengatakan “lihat/tonton”, kata kerja yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 3 },
    { id: 304, stage_code: 'A2', material_code: 'L5_C4', question_text: '먹어요 (meo-geo-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 4 },
    { id: 305, stage_code: 'A2', material_code: 'L5_C4', question_text: 'Saat ingin mengatakan “beli”, kata kerja Korea yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 5 },
    { id: 306, stage_code: 'A2', material_code: 'L5_C4', question_text: '마셔요 (ma-syeo-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 6 },
    { id: 307, stage_code: 'A2', material_code: 'L5_C4', question_text: 'Jika kamu ingin mengatakan “saya makan”, kata kerja yang paling tepat digunakan adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 7 },
    { id: 308, stage_code: 'A2', material_code: 'L5_C4', question_text: 'Jika konteksnya membeli sesuatu saat belanja, kata kerja yang tepat adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 8 },
    { id: 309, stage_code: 'A2', material_code: 'L5_C4', question_text: 'Pasangan arti yang benar adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 9 },
    { id: 310, stage_code: 'A2', material_code: 'L5_C4', question_text: 'Pasangan kata kerja untuk “makan” and “minum” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 10 },
    { id: 311, stage_code: 'A2', material_code: 'L5_C5', question_text: 'Pola S + V digunakan untuk kalimat sederhana yang berisi ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 11 },
    { id: 312, stage_code: 'A2', material_code: 'L5_C5', question_text: '저는 밥을 먹어요 (jeo-neun ba-beul meo-geo-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 12 },
    { id: 313, stage_code: 'A2', material_code: 'L5_C5', question_text: 'Kalimat yang tepat untuk “Saya makan nasi” adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 13 },
    { id: 314, stage_code: 'A2', material_code: 'L5_C5', question_text: '저는 커피를 마셔요 (jeo-neun keo-pi-reul ma-syeo-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 14 },
    { id: 315, stage_code: 'A2', material_code: 'L5_C5', question_text: 'Kalimat yang tepat untuk “Saya minum kopi” adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 15 },
    { id: 316, stage_code: 'A2', material_code: 'L5_C5', question_text: 'Pola N + 이/가 + Kata Sifat digunakan untuk menyatakan ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 16 },
    { id: 317, stage_code: 'A2', material_code: 'L5_C5', question_text: '가방이 비싸요 (ga-bang-i bi-ssa-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 17 },
    { id: 318, stage_code: 'A2', material_code: 'L5_C5', question_text: 'Kalimat yang tepat untuk “Tas mahal” adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 18 },
    { id: 319, stage_code: 'A2', material_code: 'L5_C5', question_text: '커피가 가까워요 (keo-pi-ga ga-kka-wo-yo) berarti ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 19 },
    { id: 320, stage_code: 'A2', material_code: 'L5_C5', question_text: 'Kalimat yang memakai pola N + 이/가 + Kata Sifat adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 20 },
    { id: 321, stage_code: 'A2', material_code: 'L6_C1', question_text: 'Angka Sino untuk 0 adalah ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 21 },
    { id: 322, stage_code: 'A2', material_code: 'L6_C1', question_text: 'Angka Sino untuk 1 adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 22 },
    { id: 323, stage_code: 'A2', material_code: 'L6_C1', question_text: '삼 adalah angka ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 23 },
    { id: 324, stage_code: 'A2', material_code: 'L6_C1', question_text: 'Angka Sino untuk 4 adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 24 },
    { id: 325, stage_code: 'A2', material_code: 'L6_C1', question_text: '오 adalah angka ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 25 },
    { id: 326, stage_code: 'A2', material_code: 'L6_C1', question_text: 'Angka Sino untuk 7 adalah ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 26 },
    { id: 327, stage_code: 'A2', material_code: 'L6_C1', question_text: '구 adalah angka ...', question_type: 'multiple_choice', correct_answer: 'C', question_order: 27 },
    { id: 328, stage_code: 'A2', material_code: 'L6_C1', question_text: 'Angka Sino untuk 10 adalah ...', question_type: 'multiple_choice', correct_answer: 'D', question_order: 28 },
    { id: 329, stage_code: 'A2', material_code: 'L6_C1', question_text: 'Pasangan angka Sino yang benar adalah ...', question_type: 'multiple_choice', correct_answer: 'A', question_order: 29 },
    { id: 330, stage_code: 'A2', material_code: 'L6_C2', question_text: '이거 얼마예요? (i-geo eol-ma-ye-yo?) berarti ...', question_type: 'multiple_choice', correct_answer: 'B', question_order: 30 }
  ];

  console.log("Memulai seeding data quiz_questions...");

  for (const q of questions) {
    await db.query(
      `
      INSERT INTO quiz_questions (id, stage_code, material_code, question_text, question_type, correct_answer, question_order) 
      VALUES (?, ?, ?, ?, ?, ?, ?)
      ON DUPLICATE KEY UPDATE question_text = VALUES(question_text)
      `,
      [q.id, q.stage_code, q.material_code, q.question_text, q.question_type, q.correct_answer, q.question_order]
    );
  }

  console.log(`Berhasil memasukkan ${questions.length} data ke quiz_questions.`);
}