export default async function seedQuizOptions(db) {
  const options = [
    { question_id: 1, option_key: 'A', option_text: 'ㅏ' },
    { question_id: 1, option_key: 'B', option_text: 'ㅓ' },
    { question_id: 1, option_key: 'C', option_text: 'ㅗ' },
    { question_id: 1, option_key: 'D', option_text: 'ㅜ' },
    { question_id: 2, option_key: 'A', option_text: 'a' },
    { question_id: 2, option_key: 'B', option_text: 'ya' },
    { question_id: 2, option_key: 'C', option_text: 'eo' },
    { question_id: 2, option_key: 'D', option_text: 'yo' },
    { question_id: 3, option_key: 'A', option_text: 'ㅓ' },
    { question_id: 3, option_key: 'B', option_text: 'ㅕ' },
    { question_id: 3, option_key: 'C', option_text: 'ㅗ' },
    { question_id: 3, option_key: 'D', option_text: 'ㅜ' },
    { question_id: 4, option_key: 'A', option_text: 'eo' },
    { question_id: 4, option_key: 'B', option_text: 'yeo' },
    { question_id: 4, option_key: 'C', option_text: 'o' },
    { question_id: 4, option_key: 'D', option_text: 'yo' },
    { question_id: 5, option_key: 'A', option_text: 'ㅗ' },
    { question_id: 5, option_key: 'B', option_text: 'ㅛ' },
    { question_id: 5, option_key: 'C', option_text: 'ㅜ' },
    { question_id: 5, option_key: 'D', option_text: 'ㅠ' },
    { question_id: 6, option_key: 'A', option_text: 'o' },
    { question_id: 6, option_key: 'B', option_text: 'yo' },
    { question_id: 6, option_key: 'C', option_text: 'u' },
    { question_id: 6, option_key: 'D', option_text: 'yu' },
    { question_id: 7, option_key: 'A', option_text: 'ㅗ' },
    { question_id: 7, option_key: 'B', option_text: 'ㅛ' },
    { question_id: 7, option_key: 'C', option_text: 'ㅜ' },
    { question_id: 7, option_key: 'D', option_text: 'ㅠ' },
    { question_id: 8, option_key: 'A', option_text: 'u' },
    { question_id: 8, option_key: 'B', option_text: 'yu' },
    { question_id: 8, option_key: 'C', option_text: 'eu' },
    { question_id: 8, option_key: 'D', option_text: 'i' },
    { question_id: 9, option_key: 'A', option_text: 'ㅡ' },
    { question_id: 9, option_key: 'B', option_text: 'ㅣ' },
    { question_id: 9, option_key: 'C', option_text: 'ㅓ' },
    { question_id: 9, option_key: 'D', option_text: 'ㅜ' },
    { question_id: 10, option_key: 'A', option_text: 'eu' },
    { question_id: 10, option_key: 'B', option_text: 'i' },
    { question_id: 10, option_key: 'C', option_text: 'a' },
    { question_id: 10, option_key: 'D', option_text: 'eo' },
    { question_id: 11, option_key: 'A', option_text: 'ae' },
    { question_id: 11, option_key: 'B', option_text: 'yae' },
    { question_id: 11, option_key: 'C', option_text: 'e' },
    { question_id: 11, option_key: 'D', option_text: 'ye' },
    { question_id: 12, option_key: 'A', option_text: 'ae' },
    { question_id: 12, option_key: 'B', option_text: 'yae' },
    { question_id: 12, option_key: 'C', option_text: 'e' },
    { question_id: 12, option_key: 'D', option_text: 'ye' },
    { question_id: 13, option_key: 'A', option_text: 'ae' },
    { question_id: 13, option_key: 'B', option_text: 'yae' },
    { question_id: 13, option_key: 'C', option_text: 'e' },
    { question_id: 13, option_key: 'D', option_text: 'ye' },
    { question_id: 14, option_key: 'A', option_text: 'ae' },
    { question_id: 14, option_key: 'B', option_text: 'yae' },
    { question_id: 14, option_key: 'C', option_text: 'e' },
    { question_id: 14, option_key: 'D', option_text: 'ye' },
    { question_id: 15, option_key: 'A', option_text: 'ㅢ' },
    { question_id: 15, option_key: 'B', option_text: 'ㅘ' },
    { question_id: 15, option_key: 'C', option_text: 'ㅝ' },
    { question_id: 15, option_key: 'D', option_text: 'ㅙ' },
    { question_id: 16, option_key: 'A', option_text: 'wa' },
    { question_id: 16, option_key: 'B', option_text: 'wo' },
    { question_id: 16, option_key: 'C', option_text: 'wi' },
    { question_id: 16, option_key: 'D', option_text: 'we' },
    { question_id: 17, option_key: 'A', option_text: 'wa' },
    { question_id: 17, option_key: 'B', option_text: 'wo' },
    { question_id: 17, option_key: 'C', option_text: 'wi' },
    { question_id: 17, option_key: 'D', option_text: 'we' },
    { question_id: 18, option_key: 'A', option_text: 'wa' },
    { question_id: 18, option_key: 'B', option_text: 'wo' },
    { question_id: 18, option_key: 'C', option_text: 'wi' },
    { question_id: 18, option_key: 'D', option_text: 'we' },
    { question_id: 19, option_key: 'A', option_text: 'oe/we' },
    { question_id: 19, option_key: 'B', option_text: 'wa' },
    { question_id: 19, option_key: 'C', option_text: 'wi' },
    { question_id: 19, option_key: 'D', option_text: 'ui' },
    { question_id: 20, option_key: 'A', option_text: 'wae' },
    { question_id: 20, option_key: 'B', option_text: 'we' },
    { question_id: 20, option_key: 'C', option_text: 'yae' },
    { question_id: 20, option_key: 'D', option_text: 'e' },
    { question_id: 21, option_key: 'A', option_text: 'g/k' },
    { question_id: 21, option_key: 'B', option_text: 'n' },
    { question_id: 21, option_key: 'C', option_text: 'd/t' },
    { question_id: 21, option_key: 'D', option_text: 'r/l' },
    { question_id: 22, option_key: 'A', option_text: 'g/k' },
    { question_id: 22, option_key: 'B', option_text: 'n' },
    { question_id: 22, option_key: 'C', option_text: 'd/t' },
    { question_id: 22, option_key: 'D', option_text: 'm' },
    { question_id: 23, option_key: 'A', option_text: 'd/t' },
    { question_id: 23, option_key: 'B', option_text: 'r/l' },
    { question_id: 23, option_key: 'C', option_text: 'b/p' },
    { question_id: 23, option_key: 'D', option_text: 's' },
    { question_id: 24, option_key: 'A', option_text: 'n' },
    { question_id: 24, option_key: 'B', option_text: 'd/t' },
    { question_id: 24, option_key: 'C', option_text: 'r/l' },
    { question_id: 24, option_key: 'D', option_text: 'm' },
    { question_id: 25, option_key: 'A', option_text: 'm' },
    { question_id: 25, option_key: 'B', option_text: 'b/p' },
    { question_id: 25, option_key: 'C', option_text: 's' },
    { question_id: 25, option_key: 'D', option_text: 'j' },
    { question_id: 26, option_key: 'A', option_text: 'b/p' },
    { question_id: 26, option_key: 'B', option_text: 's' },
    { question_id: 26, option_key: 'C', option_text: 'silent/ng' },
    { question_id: 26, option_key: 'D', option_text: 'j' },
    { question_id: 27, option_key: 'A', option_text: 's' },
    { question_id: 27, option_key: 'B', option_text: 'j' },
    { question_id: 27, option_key: 'C', option_text: 'ch' },
    { question_id: 27, option_key: 'D', option_text: 'k' },
    { question_id: 28, option_key: 'A', option_text: 's' },
    { question_id: 28, option_key: 'B', option_text: 'silent awal / ng akhir' },
    { question_id: 28, option_key: 'C', option_text: 'j' },
    { question_id: 28, option_key: 'D', option_text: 'h' },
    { question_id: 29, option_key: 'A', option_text: 'ga' },
    { question_id: 29, option_key: 'B', option_text: 'na' },
    { question_id: 29, option_key: 'C', option_text: 'da' },
    { question_id: 29, option_key: 'D', option_text: 'ma' },
    { question_id: 30, option_key: 'A', option_text: 'ba' },
    { question_id: 30, option_key: 'B', option_text: 'sa' },
    { question_id: 30, option_key: 'C', option_text: 'ja' },
    { question_id: 30, option_key: 'D', option_text: 'ra/la' },
    { question_id: 31, option_key: 'A', option_text: 'kk' },
    { question_id: 31, option_key: 'B', option_text: 'tt' },
    { question_id: 31, option_key: 'C', option_text: 'pp' },
    { question_id: 31, option_key: 'D', option_text: 'ss' },
    { question_id: 32, option_key: 'A', option_text: 'kk' },
    { question_id: 32, option_key: 'B', option_text: 'tt' },
    { question_id: 32, option_key: 'C', option_text: 'pp' },
    { question_id: 32, option_key: 'D', option_text: 'jj' },
    { question_id: 33, option_key: 'A', option_text: 'pp' },
    { question_id: 33, option_key: 'B', option_text: 'ss' },
    { question_id: 33, option_key: 'C', option_text: 'jj' },
    { question_id: 33, option_key: 'D', option_text: 'kk' },
    { question_id: 34, option_key: 'A', option_text: 'ss' },
    { question_id: 34, option_key: 'B', option_text: 'kk' },
    { question_id: 34, option_key: 'C', option_text: 'tt' },
    { question_id: 34, option_key: 'D', option_text: 'pp' },
    { question_id: 35, option_key: 'A', option_text: 'jj' },
    { question_id: 35, option_key: 'B', option_text: 'ss' },
    { question_id: 35, option_key: 'C', option_text: 'tt' },
    { question_id: 35, option_key: 'D', option_text: 'kk' },
    { question_id: 36, option_key: 'A', option_text: 'biasa/lemah' },
    { question_id: 36, option_key: 'B', option_text: 'lebih kuat/tegang' },
    { question_id: 36, option_key: 'C', option_text: 'tidak dibaca' },
    { question_id: 36, option_key: 'D', option_text: 'berubah menjadi ng' },
    { question_id: 37, option_key: 'A', option_text: 'kki' },
    { question_id: 37, option_key: 'B', option_text: 'tta' },
    { question_id: 37, option_key: 'C', option_text: 'ppa' },
    { question_id: 37, option_key: 'D', option_text: 'ssi' },
    { question_id: 38, option_key: 'A', option_text: 'kki' },
    { question_id: 38, option_key: 'B', option_text: 'tta' },
    { question_id: 38, option_key: 'C', option_text: 'ppa' },
    { question_id: 38, option_key: 'D', option_text: 'jja' },
    { question_id: 39, option_key: 'A', option_text: 'ppa' },
    { question_id: 39, option_key: 'B', option_text: 'ssi' },
    { question_id: 39, option_key: 'C', option_text: 'jja' },
    { question_id: 39, option_key: 'D', option_text: 'tta' },
    { question_id: 40, option_key: 'A', option_text: 'ssi' },
    { question_id: 40, option_key: 'B', option_text: 'jja' },
    { question_id: 40, option_key: 'C', option_text: 'ppa' },
    { question_id: 40, option_key: 'D', option_text: 'kki' },
    { question_id: 41, option_key: 'A', option_text: 'jja' },
    { question_id: 41, option_key: 'B', option_text: 'ssi' },
    { question_id: 41, option_key: 'C', option_text: 'tta' },
    { question_id: 41, option_key: 'D', option_text: 'kki' },
    { question_id: 42, option_key: 'A', option_text: 'k' },
    { question_id: 42, option_key: 'B', option_text: 'n' },
    { question_id: 42, option_key: 'C', option_text: 't' },
    { question_id: 42, option_key: 'D', option_text: 'l' },
    { question_id: 43, option_key: 'A', option_text: 'k' },
    { question_id: 43, option_key: 'B', option_text: 'n' },
    { question_id: 43, option_key: 'C', option_text: 't' },
    { question_id: 43, option_key: 'D', option_text: 'l' },
    { question_id: 44, option_key: 'A', option_text: 'k' },
    { question_id: 44, option_key: 'B', option_text: 'n' },
    { question_id: 44, option_key: 'C', option_text: 't' },
    { question_id: 44, option_key: 'D', option_text: 'p' },
    { question_id: 45, option_key: 'A', option_text: 'l' },
    { question_id: 45, option_key: 'B', option_text: 'm' },
    { question_id: 45, option_key: 'C', option_text: 'p' },
    { question_id: 45, option_key: 'D', option_text: 'ng' },
    { question_id: 46, option_key: 'A', option_text: 'l' },
    { question_id: 46, option_key: 'B', option_text: 'm' },
    { question_id: 46, option_key: 'C', option_text: 'p' },
    { question_id: 46, option_key: 'D', option_text: 'ng' },
    { question_id: 47, option_key: 'A', option_text: 'p' },
    { question_id: 47, option_key: 'B', option_text: 'm' },
    { question_id: 47, option_key: 'C', option_text: 't' },
    { question_id: 47, option_key: 'D', option_text: 'k' },
    { question_id: 48, option_key: 'A', option_text: 'ng' },
    { question_id: 48, option_key: 'B', option_text: 'p' },
    { question_id: 48, option_key: 'C', option_text: 't' },
    { question_id: 48, option_key: 'D', option_text: 'l' },
    { question_id: 49, option_key: 'A', option_text: 'gak' },
    { question_id: 49, option_key: 'B', option_text: 'an' },
    { question_id: 49, option_key: 'C', option_text: 'dat' },
    { question_id: 49, option_key: 'D', option_text: 'gal' },
    { question_id: 50, option_key: 'A', option_text: 'gak' },
    { question_id: 50, option_key: 'B', option_text: 'an' },
    { question_id: 50, option_key: 'C', option_text: 'dat' },
    { question_id: 50, option_key: 'D', option_text: 'sam' },
    { question_id: 51, option_key: 'A', option_text: 'dat' },
    { question_id: 51, option_key: 'B', option_text: 'gal' },
    { question_id: 51, option_key: 'C', option_text: 'bap' },
    { question_id: 51, option_key: 'D', option_text: 'yeong' },
    { question_id: 52, option_key: 'A', option_text: 'gal' },
    { question_id: 52, option_key: 'B', option_text: 'sam' },
    { question_id: 52, option_key: 'C', option_text: 'bap' },
    { question_id: 52, option_key: 'D', option_text: 'an' },
    { question_id: 53, option_key: 'A', option_text: 'sam' },
    { question_id: 53, option_key: 'B', option_text: 'bap' },
    { question_id: 53, option_key: 'C', option_text: 'yeong' },
    { question_id: 53, option_key: 'D', option_text: 'dat' },
    { question_id: 54, option_key: 'A', option_text: 'bap' },
    { question_id: 54, option_key: 'B', option_text: 'gak' },
    { question_id: 54, option_key: 'C', option_text: 'gal' },
    { question_id: 54, option_key: 'D', option_text: 'an' },
    { question_id: 55, option_key: 'A', option_text: 'yeong' },
    { question_id: 55, option_key: 'B', option_text: 'sam' },
    { question_id: 55, option_key: 'C', option_text: 'dat' },
    { question_id: 55, option_key: 'D', option_text: 'bap' },
    { question_id: 56, option_key: 'A', option_text: 'sak' },
    { question_id: 56, option_key: 'B', option_text: 'man-ta' },
    { question_id: 56, option_key: 'C', option_text: 'an-da' },
    { question_id: 56, option_key: 'D', option_text: 'yeo-deol' },
    { question_id: 57, option_key: 'A', option_text: 'man-ta' },
    { question_id: 57, option_key: 'B', option_text: 'an-da' },
    { question_id: 57, option_key: 'C', option_text: 'yeo-deol' },
    { question_id: 57, option_key: 'D', option_text: 'hal-ta' },
    { question_id: 58, option_key: 'A', option_text: 'eop-da' },
    { question_id: 58, option_key: 'B', option_text: 'an-da' },
    { question_id: 58, option_key: 'C', option_text: 'gap' },
    { question_id: 58, option_key: 'D', option_text: 'sak' },
    { question_id: 59, option_key: 'A', option_text: 'eop-sseo' },
    { question_id: 59, option_key: 'B', option_text: 'i-sseo' },
    { question_id: 59, option_key: 'C', option_text: 'i-beo-yo' },
    { question_id: 59, option_key: 'D', option_text: 'meo-geo-yo' },
    { question_id: 60, option_key: 'A', option_text: 'meo-geo-yo' },
    { question_id: 60, option_key: 'B', option_text: 'i-sseo' },
    { question_id: 60, option_key: 'C', option_text: 'i-beo-yo' },
    { question_id: 60, option_key: 'D', option_text: 'eop-sseo' },
    { question_id: 61, option_key: 'A', option_text: 'Ini apa?' },
    { question_id: 61, option_key: 'B', option_text: 'Siapa nama kamu?' },
    { question_id: 61, option_key: 'C', option_text: 'Ini paspor' },
    { question_id: 61, option_key: 'D', option_text: 'Ini kamera' },
    { question_id: 62, option_key: 'A', option_text: 'nama' },
    { question_id: 62, option_key: 'B', option_text: 'paspor' },
    { question_id: 62, option_key: 'C', option_text: 'kamera' },
    { question_id: 62, option_key: 'D', option_text: 'tas' },
    { question_id: 63, option_key: 'A', option_text: '제 이름은 Jessica예요 (je i-reum-eun Jessica-ye-yo)' },
    { question_id: 63, option_key: 'B', option_text: '이름이 뭐예요? (i-reum-i mwo-ye-yo?)' },
    { question_id: 63, option_key: 'C', option_text: '이게 뭐예요? (i-ge mwo-ye-yo?)' },
    { question_id: 63, option_key: 'D', option_text: '가방이에요 (ga-bang-i-e-yo)' },
    { question_id: 64, option_key: 'A', option_text: 'Siapa nama kamu?' },
    { question_id: 64, option_key: 'B', option_text: 'Nama saya Jessica' },
    { question_id: 64, option_key: 'C', option_text: 'Ini Jessica' },
    { question_id: 64, option_key: 'D', option_text: 'Ini nama' },
    { question_id: 65, option_key: 'A', option_text: '이름이 뭐예요? (i-reum-i mwo-ye-yo?)' },
    { question_id: 65, option_key: 'B', option_text: '여권이에요 (yeo-gwon-i-e-yo)' },
    { question_id: 65, option_key: 'C', option_text: '가방이에요 (ga-bang-i-e-yo)' },
    { question_id: 65, option_key: 'D', option_text: '카메라예요 (ka-me-ra-ye-yo)' },
    { question_id: 66, option_key: 'A', option_text: 'nama' },
    { question_id: 66, option_key: 'B', option_text: 'tas' },
    { question_id: 66, option_key: 'C', option_text: 'kamera' },
    { question_id: 66, option_key: 'D', option_text: 'paspor' },
    { question_id: 67, option_key: 'A', option_text: 'siapa' },
    { question_id: 67, option_key: 'B', option_text: 'adalah' },
    { question_id: 67, option_key: 'C', option_text: 'apa' },
    { question_id: 67, option_key: 'D', option_text: 'nama' },
    { question_id: 68, option_key: 'A', option_text: '예요 (ye-yo)' },
    { question_id: 68, option_key: 'B', option_text: '이에요 (i-e-yo)' },
    { question_id: 68, option_key: 'C', option_text: '은 (eun)' },
    { question_id: 68, option_key: 'D', option_text: '는 (neun)' },
    { question_id: 69, option_key: 'A', option_text: '이에요 (i-e-yo)' },
    { question_id: 69, option_key: 'B', option_text: '예요 (ye-yo)' },
    { question_id: 69, option_key: 'C', option_text: '은 (eun)' },
    { question_id: 69, option_key: 'D', option_text: '는 (neun)' },
    { question_id: 70, option_key: 'A', option_text: '여권이에요 (yeo-gwon-i-e-yo)' },
    { question_id: 70, option_key: 'B', option_text: '가방이에요 (ga-bang-i-e-yo)' },
    { question_id: 70, option_key: 'C', option_text: '카메라예요 (ka-me-ra-ye-yo)' },
    { question_id: 70, option_key: 'D', option_text: '이름이에요 (i-reum-i-e-yo)' },
    { question_id: 71, option_key: 'A', option_text: 'Ini paspor' },
    { question_id: 71, option_key: 'B', option_text: 'Ini tas' },
    { question_id: 71, option_key: 'C', option_text: 'Ini kamera' },
    { question_id: 71, option_key: 'D', option_text: 'Ini nama' },
    { question_id: 72, option_key: 'A', option_text: 'Ini kamera' },
    { question_id: 72, option_key: 'B', option_text: 'Ini tas' },
    { question_id: 72, option_key: 'C', option_text: 'Ini paspor' },
    { question_id: 72, option_key: 'D', option_text: 'Ini nama' },
    { question_id: 73, option_key: 'A', option_text: 'berakhiran konsonan' },
    { question_id: 73, option_key: 'B', option_text: 'berakhiran vokal' },
    { question_id: 73, option_key: 'C', option_text: 'berarti nama' },
    { question_id: 73, option_key: 'D', option_text: 'berarti kamera' },
    { question_id: 74, option_key: 'A', option_text: 'berakhiran konsonan' },
    { question_id: 74, option_key: 'B', option_text: 'berakhiran vokal' },
    { question_id: 74, option_key: 'C', option_text: 'berarti paspor' },
    { question_id: 74, option_key: 'D', option_text: 'berarti tas' },
    { question_id: 75, option_key: 'A', option_text: '가방이에요 (ga-bang-i-e-yo)' },
    { question_id: 75, option_key: 'B', option_text: '여권이에요 (yeo-gwon-i-e-yo)' },
    { question_id: 75, option_key: 'C', option_text: '카메라예요 (ka-me-ra-ye-yo)' },
    { question_id: 75, option_key: 'D', option_text: '이름이에요 (i-reum-i-e-yo)' },
    { question_id: 76, option_key: 'A', option_text: 'Ini apa?' },
    { question_id: 76, option_key: 'B', option_text: 'Siapa nama kamu?' },
    { question_id: 76, option_key: 'C', option_text: 'Ini tas' },
    { question_id: 76, option_key: 'D', option_text: 'Ini paspor' },
    { question_id: 77, option_key: 'A', option_text: '가방이에요 (ga-bang-i-e-yo)' },
    { question_id: 77, option_key: 'B', option_text: '여권이에요 (yeo-gwon-i-e-yo)' },
    { question_id: 77, option_key: 'C', option_text: '카메라예요 (ka-me-ra-ye-yo)' },
    { question_id: 77, option_key: 'D', option_text: '선글라스예요 (seon-geul-la-seu-ye-yo)' },
    { question_id: 78, option_key: 'A', option_text: '여권이에요 (yeo-gwon-i-e-yo)' },
    { question_id: 78, option_key: 'B', option_text: '가방이에요 (ga-bang-i-e-yo)' },
    { question_id: 78, option_key: 'C', option_text: '카메라예요 (ka-me-ra-ye-yo)' },
    { question_id: 78, option_key: 'D', option_text: '이름이에요 (i-reum-i-e-yo)' },
    { question_id: 79, option_key: 'A', option_text: '카메라예요 (ka-me-ra-ye-yo)' },
    { question_id: 79, option_key: 'B', option_text: '가방이에요 (ga-bang-i-e-yo)' },
    { question_id: 79, option_key: 'C', option_text: '여권이에요 (yeo-gwon-i-e-yo)' },
    { question_id: 79, option_key: 'D', option_text: '선글라스예요 (seon-geul-la-seu-ye-yo)' },
    { question_id: 80, option_key: 'A', option_text: '선글라스예요 (seon-geul-la-seu-ye-yo)' },
    { question_id: 80, option_key: 'B', option_text: '카메라예요 (ka-me-ra-ye-yo)' },
    { question_id: 80, option_key: 'C', option_text: '가방이에요 (ga-bang-i-e-yo)' },
    { question_id: 80, option_key: 'D', option_text: '여권이에요 (yeo-gwon-i-e-yo)' },
    { question_id: 81, option_key: 'A', option_text: '이게 뭐예요? (i-ge mwo-ye-yo?) → 가방이에요 (ga-bang-i-e-yo)' },
    { question_id: 81, option_key: 'B', option_text: '이름이 뭐예요? (i-reum-i mwo-ye-yo?) → 카메라예요 (ka-me-ra-ye-yo)' },
    { question_id: 81, option_key: 'C', option_text: '이게 뭐예요? (i-ge mwo-ye-yo?) → 제 이름은 Jessica예요 (je i-reum-eun Jessica-ye-yo)' },
    { question_id: 81, option_key: 'D', option_text: '여권이에요 (yeo-gwon-i-e-yo) → 이름이 뭐예요? (i-reum-i mwo-ye-yo?)' },
    { question_id: 82, option_key: 'A', option_text: '이게 뭐예요? (i-ge mwo-ye-yo?)' },
    { question_id: 82, option_key: 'B', option_text: '이름이 뭐예요? (i-reum-i mwo-ye-yo?)' },
    { question_id: 82, option_key: 'C', option_text: '제 이름은 Jessica예요 (je i-reum-eun Jessica-ye-yo)' },
    { question_id: 82, option_key: 'D', option_text: '저는 학생이에요 (jeo-neun hak-saeng-i-e-yo)' },
    { question_id: 83, option_key: 'A', option_text: 'penanda topik' },
    { question_id: 83, option_key: 'B', option_text: 'penanda benda' },
    { question_id: 83, option_key: 'C', option_text: 'kata tanya' },
    { question_id: 83, option_key: 'D', option_text: 'akhiran benda' },
    { question_id: 84, option_key: 'A', option_text: '은 (eun)' },
    { question_id: 84, option_key: 'B', option_text: '는 (neun)' },
    { question_id: 84, option_key: 'C', option_text: '이에요 (i-e-yo)' },
    { question_id: 84, option_key: 'D', option_text: '예요 (ye-yo)' },
    { question_id: 85, option_key: 'A', option_text: '은 (eun)' },
    { question_id: 85, option_key: 'B', option_text: '는 (neun)' },
    { question_id: 85, option_key: 'C', option_text: '이에요 (i-e-yo)' },
    { question_id: 85, option_key: 'D', option_text: '예요 (ye-yo)' },
    { question_id: 86, option_key: 'A', option_text: 'Saya adalah siswa' },
    { question_id: 86, option_key: 'B', option_text: 'Ini paspor' },
    { question_id: 86, option_key: 'C', option_text: 'Nama saya Jessica' },
    { question_id: 86, option_key: 'D', option_text: 'Ini kamera' },
    { question_id: 87, option_key: 'A', option_text: '저 (jeo)' },
    { question_id: 87, option_key: 'B', option_text: '는 (neun)' },
    { question_id: 87, option_key: 'C', option_text: '학생 (hak-saeng)' },
    { question_id: 87, option_key: 'D', option_text: '이에요 (i-e-yo)' },
    { question_id: 88, option_key: 'A', option_text: 'Jeonghan adalah penyanyi' },
    { question_id: 88, option_key: 'B', option_text: 'Jeonghan adalah siswa' },
    { question_id: 88, option_key: 'C', option_text: 'Ini penyanyi' },
    { question_id: 88, option_key: 'D', option_text: 'Nama saya Jeonghan' },
    { question_id: 89, option_key: 'A', option_text: 'Karena berakhiran konsonan' },
    { question_id: 89, option_key: 'B', option_text: 'Karena berakhiran vokal' },
    { question_id: 89, option_key: 'C', option_text: 'Karena berarti penyanyi' },
    { question_id: 89, option_key: 'D', option_text: 'Karena berarti siswa' },
    { question_id: 90, option_key: 'A', option_text: '저는 학생이에요 (jeo-neun hak-saeng-i-e-yo)' },
    { question_id: 90, option_key: 'B', option_text: '저은 학생이에요 (jeo-eun hak-saeng-i-e-yo)' },
    { question_id: 90, option_key: 'C', option_text: '정한는 가수예요 (jeong-han-neun ga-su-ye-yo)' },
    { question_id: 90, option_key: 'D', option_text: '카메라은 예요 (ka-me-ra-eun ye-yo)' },
    { question_id: 91, option_key: 'A', option_text: 'Terima kasih' },
    { question_id: 91, option_key: 'B', option_text: 'Halo' },
    { question_id: 91, option_key: 'C', option_text: 'Maaf' },
    { question_id: 91, option_key: 'D', option_text: 'Sampai jumpa' },
    { question_id: 92, option_key: 'A', option_text: '감사합니다 (gam-sa-ham-ni-da)' },
    { question_id: 92, option_key: 'B', option_text: '미안합니다 (mi-an-ham-ni-da)' },
    { question_id: 92, option_key: 'C', option_text: '안녕하십니까 (an-nyeong-ha-sim-ni-kka)' },
    { question_id: 92, option_key: 'D', option_text: '괜찮습니다 (gwaen-chan-seum-ni-da)' },
    { question_id: 93, option_key: 'A', option_text: 'Halo' },
    { question_id: 93, option_key: 'B', option_text: 'Maaf' },
    { question_id: 93, option_key: 'C', option_text: 'Selamat jalan' },
    { question_id: 93, option_key: 'D', option_text: 'Terima kasih' },
    { question_id: 94, option_key: 'A', option_text: '미안합니다 (mi-an-ham-ni-da)' },
    { question_id: 94, option_key: 'B', option_text: '감사합니다 (gam-sa-ham-ni-da)' },
    { question_id: 94, option_key: 'C', option_text: '안녕하세요 (an-nyeong-ha-se-yo)' },
    { question_id: 94, option_key: 'D', option_text: '반가워요 (man-na-seo ban-ga-wo-yo)' },
    { question_id: 95, option_key: 'A', option_text: 'Maaf sopan' },
    { question_id: 95, option_key: 'B', option_text: 'Halo formal' },
    { question_id: 95, option_key: 'C', option_text: 'Terima kasih informal' },
    { question_id: 95, option_key: 'D', option_text: 'Senang bertemu' },
    { question_id: 96, option_key: 'A', option_text: '안녕히 가세요 (an-nyeong-hi ga-se-yo)' },
    { question_id: 96, option_key: 'B', option_text: '고마워요 (go-ma-wo-yo)' },
    { question_id: 96, option_key: 'C', option_text: '안녕하세요 (an-nyeong-ha-se-yo)' },
    { question_id: 96, option_key: 'D', option_text: '미안합니다 (mi-an-ham-ni-da)' },
    { question_id: 97, option_key: 'A', option_text: 'Maaf sopan' },
    { question_id: 97, option_key: 'B', option_text: 'Halo' },
    { question_id: 97, option_key: 'C', option_text: 'Terima kasih' },
    { question_id: 97, option_key: 'D', option_text: 'Selamat jalan' },
    { question_id: 98, option_key: 'A', option_text: '안녕하세요 (an-nyeong-ha-se-yo)' },
    { question_id: 98, option_key: 'B', option_text: '안녕히 가세요 (an-nyeong-hi ga-se-yo)' },
    { question_id: 98, option_key: 'C', option_text: '괜찮습니다 (gwaen-chan-seum-ni-da)' },
    { question_id: 98, option_key: 'D', option_text: '반가워요 (man-na-seo ban-ga-wo-yo)' },
    { question_id: 99, option_key: 'A', option_text: 'Terima kasih' },
    { question_id: 99, option_key: 'B', option_text: 'Halo' },
    { question_id: 99, option_key: 'C', option_text: 'Selamat tinggal' },
    { question_id: 99, option_key: 'D', option_text: 'Maaf' },
    { question_id: 100, option_key: 'A', option_text: 'Selamat jalan' },
    { question_id: 100, option_key: 'B', option_text: 'Maaf' },
    { question_id: 100, option_key: 'C', option_text: 'Terima kasih' },
    { question_id: 100, option_key: 'D', option_text: 'Senang bertemu' },
    { question_id: 101, option_key: 'A', option_text: 'tiket pesawat' },
    { question_id: 101, option_key: 'B', option_text: 'paspor' },
    { question_id: 101, option_key: 'C', option_text: 'tas' },
    { question_id: 101, option_key: 'D', option_text: 'kamera' },
    { question_id: 102, option_key: 'A', option_text: '비행기표 (bi-haeng-gi-pyo)' },
    { question_id: 102, option_key: 'B', option_text: '가방 (ga-bang)' },
    { question_id: 102, option_key: 'C', option_text: '여권 (yeo-gwon)' },
    { question_id: 102, option_key: 'D', option_text: '공항 (gong-hang)' },
    { question_id: 103, option_key: 'A', option_text: 'kamera' },
    { question_id: 103, option_key: 'B', option_text: 'tas' },
    { question_id: 103, option_key: 'C', option_text: 'bandara' },
    { question_id: 103, option_key: 'D', option_text: 'koper' },
    { question_id: 104, option_key: 'A', option_text: '케리어 (ke-ri-eo)' },
    { question_id: 104, option_key: 'B', option_text: '카메라 (ka-me-ra)' },
    { question_id: 104, option_key: 'C', option_text: '가방 (ga-bang)' },
    { question_id: 104, option_key: 'D', option_text: '선글라스 (seon-geul-la-seu)' },
    { question_id: 105, option_key: 'A', option_text: 'koper' },
    { question_id: 105, option_key: 'B', option_text: 'tiket pesawat' },
    { question_id: 105, option_key: 'C', option_text: 'kamera' },
    { question_id: 105, option_key: 'D', option_text: 'paspor' },
    { question_id: 106, option_key: 'A', option_text: '여권 (yeo-gwon)' },
    { question_id: 106, option_key: 'B', option_text: '공항 (gong-hang)' },
    { question_id: 106, option_key: 'C', option_text: '은행원 (eun-haeng-won)' },
    { question_id: 106, option_key: 'D', option_text: '가방 (ga-bang)' },
    { question_id: 107, option_key: 'A', option_text: 'tiket pesawat' },
    { question_id: 107, option_key: 'B', option_text: 'pesawat' },
    { question_id: 107, option_key: 'C', option_text: 'bandara' },
    { question_id: 107, option_key: 'D', option_text: 'paspor' },
    { question_id: 108, option_key: 'A', option_text: '비행기표 (bi-haeng-gi-pyo)' },
    { question_id: 108, option_key: 'B', option_text: '비행기 (bi-haeng-gi)' },
    { question_id: 108, option_key: 'C', option_text: '공항 (gong-hang)' },
    { question_id: 108, option_key: 'D', option_text: '여권 (yeo-gwon)' },
    { question_id: 109, option_key: 'A', option_text: 'pesawat' },
    { question_id: 109, option_key: 'B', option_text: 'koper' },
    { question_id: 109, option_key: 'C', option_text: 'bandara' },
    { question_id: 109, option_key: 'D', option_text: 'kamera' },
    { question_id: 110, option_key: 'A', option_text: '카메라 (ka-me-ra)' },
    { question_id: 110, option_key: 'B', option_text: '가방 (ga-bang)' },
    { question_id: 110, option_key: 'C', option_text: '케리어 (ke-ri-eo)' },
    { question_id: 110, option_key: 'D', option_text: '선글라스 (seon-geul-la-seu)' },
    { question_id: 111, option_key: 'A', option_text: 'aktor' },
    { question_id: 111, option_key: 'B', option_text: 'penyanyi' },
    { question_id: 111, option_key: 'C', option_text: 'siswa' },
    { question_id: 111, option_key: 'D', option_text: 'polisi' },
    { question_id: 112, option_key: 'A', option_text: '가수 (ga-su)' },
    { question_id: 112, option_key: 'B', option_text: '학생 (hak-saeng)' },
    { question_id: 112, option_key: 'C', option_text: '배우 (bae-u)' },
    { question_id: 112, option_key: 'D', option_text: '의사 (ui-sa)' },
    { question_id: 113, option_key: 'A', option_text: 'guru' },
    { question_id: 113, option_key: 'B', option_text: 'dokter' },
    { question_id: 113, option_key: 'C', option_text: 'perawat' },
    { question_id: 113, option_key: 'D', option_text: 'siswa' },
    { question_id: 114, option_key: 'A', option_text: '경찰 (gyeong-chal)' },
    { question_id: 114, option_key: 'B', option_text: '선생님 (seon-saeng-nim)' },
    { question_id: 114, option_key: 'C', option_text: '요리사 (yo-ri-sa)' },
    { question_id: 114, option_key: 'D', option_text: '은행원 (eun-haeng-won)' },
    { question_id: 115, option_key: 'A', option_text: 'polisi' },
    { question_id: 115, option_key: 'B', option_text: 'dokter' },
    { question_id: 115, option_key: 'C', option_text: 'guru' },
    { question_id: 115, option_key: 'D', option_text: 'pegawai bank' },
    { question_id: 116, option_key: 'A', option_text: '학생 (hak-saeng)' },
    { question_id: 116, option_key: 'B', option_text: '간호사 (gan-ho-sa)' },
    { question_id: 116, option_key: 'C', option_text: '선생님 (seon-saeng-nim)' },
    { question_id: 116, option_key: 'D', option_text: '배우 (bae-u)' },
    { question_id: 117, option_key: 'A', option_text: 'dokter' },
    { question_id: 117, option_key: 'B', option_text: 'polisi' },
    { question_id: 117, option_key: 'C', option_text: 'koki' },
    { question_id: 117, option_key: 'D', option_text: 'perawat' },
    { question_id: 118, option_key: 'A', option_text: '요리사 (yo-ri-sa)' },
    { question_id: 118, option_key: 'B', option_text: '의사 (ui-sa)' },
    { question_id: 118, option_key: 'C', option_text: '경찰 (gyeong-chal)' },
    { question_id: 118, option_key: 'D', option_text: '가수 (ga-su)' },
    { question_id: 119, option_key: 'A', option_text: 'pegawai bank' },
    { question_id: 119, option_key: 'B', option_text: 'karyawan' },
    { question_id: 119, option_key: 'C', option_text: 'aktor' },
    { question_id: 119, option_key: 'D', option_text: 'penyanyi' },
    { question_id: 120, option_key: 'A', option_text: '회사원 (hoe-sa-won)' },
    { question_id: 120, option_key: 'B', option_text: '선생님 (seon-saeng-nim)' },
    { question_id: 120, option_key: 'C', option_text: '은행원 (eun-haeng-won)' },
    { question_id: 120, option_key: 'D', option_text: '학생 (hak-saeng)' },
    { question_id: 121, option_key: 'A', option_text: 'berterima kasih' },
    { question_id: 121, option_key: 'B', option_text: 'meminta izin/permisi' },
    { question_id: 121, option_key: 'C', option_text: 'menyebut nama benda' },
    { question_id: 121, option_key: 'D', option_text: 'menunjukkan benda jauh' },
    { question_id: 122, option_key: 'A', option_text: '물어봐도 돼요? (mu-reo-bwa-do dwae-yo?)' },
    { question_id: 122, option_key: 'B', option_text: '여기 (yeo-gi)' },
    { question_id: 122, option_key: 'C', option_text: '실례하지만 (sil-lye-ha-ji-man)' },
    { question_id: 122, option_key: 'D', option_text: '이 (i)' },
    { question_id: 123, option_key: 'A', option_text: 'Ini apa?' },
    { question_id: 123, option_key: 'B', option_text: 'Ini Gyeongbokgung' },
    { question_id: 123, option_key: 'C', option_text: 'Boleh saya bertanya?' },
    { question_id: 123, option_key: 'D', option_text: 'Silakan bicara' },
    { question_id: 124, option_key: 'A', option_text: '실례하지만, 물어봐도 돼요? (sil-lye-ha-ji-man, mu-reo-bwa-do dwae-yo?)' },
    { question_id: 124, option_key: 'B', option_text: '이 카메라예요 (i ka-me-ra-ye-yo)' },
    { question_id: 124, option_key: 'C', option_text: '저 비행기예요 (jeo bi-haeng-gi-ye-yo)' },
    { question_id: 124, option_key: 'D', option_text: '그 가방 (geu ga-bang)' },
    { question_id: 125, option_key: 'A', option_text: 'Tidak boleh bertanya' },
    { question_id: 125, option_key: 'B', option_text: 'Ya, silakan bicara' },
    { question_id: 125, option_key: 'C', option_text: 'Ini di mana?' },
    { question_id: 125, option_key: 'D', option_text: 'Itu tas' },
    { question_id: 126, option_key: 'A', option_text: '네, 말씀하세요 (ne, mal-sseum-ha-se-yo)' },
    { question_id: 126, option_key: 'B', option_text: '여기 (yeo-gi)' },
    { question_id: 126, option_key: 'C', option_text: '저 (jeo)' },
    { question_id: 126, option_key: 'D', option_text: '그 카메라 (geu ka-me-ra)' },
    { question_id: 127, option_key: 'A', option_text: 'Ini benda apa?' },
    { question_id: 127, option_key: 'B', option_text: 'Nama orang' },
    { question_id: 127, option_key: 'C', option_text: 'Di mana tempat ini?' },
    { question_id: 127, option_key: 'D', option_text: 'Apakah ini kamera?' },
    { question_id: 128, option_key: 'A', option_text: '여기 어디예요? (yeo-gi neun eo-di-ye-yo?)' },
    { question_id: 128, option_key: 'B', option_text: '여기는 경복궁이에요 (yeo-gi-neun gyeong-bok-gung-i-e-yo)' },
    { question_id: 128, option_key: 'C', option_text: '네, 말씀하세요 (ne, mal-sseum-ha-se-yo)' },
    { question_id: 128, option_key: 'D', option_text: '물어봐도 돼요? (mu-reo-bwa-do dwae-yo?)' },
    { question_id: 129, option_key: 'A', option_text: 'Ini Gyeongbokgung' },
    { question_id: 129, option_key: 'B', option_text: 'Ini kamera' },
    { question_id: 129, option_key: 'C', option_text: 'Boleh saya bertanya?' },
    { question_id: 129, option_key: 'D', option_text: 'Silakan bicara' },
    { question_id: 130, option_key: 'A', option_text: '실례하지만 (sil-lye-ha-ji-man)' },
    { question_id: 130, option_key: 'B', option_text: '여기는 경복궁이에요 (yeo-gi-neun gyeong-bok-gung-i-e-yo)' },
    { question_id: 130, option_key: 'C', option_text: '이 가방 (i ga-bang)' },
    { question_id: 130, option_key: 'D', option_text: '저 비행기 (jeo bi-haeng-gi)' },
    { question_id: 131, option_key: 'A', option_text: '네, 말씀하세요 → 실례하지만' },
    { question_id: 131, option_key: 'B', option_text: '실례하지만 → 물어봐도 돼요? → 네, 말씀하세요' },
    { question_id: 131, option_key: 'C', option_text: '여기는 경복궁이에요 → 여기 어디예요?' },
    { question_id: 131, option_key: 'D', option_text: '저 비행기 → 이 가방' },
    { question_id: 132, option_key: 'A', option_text: '그 (geu)' },
    { question_id: 132, option_key: 'B', option_text: '저 (jeo)' },
    { question_id: 132, option_key: 'C', option_text: '실례하지만 (sil-lye-ha-ji-man)' },
    { question_id: 132, option_key: 'D', option_text: '이 (i)' },
    { question_id: 133, option_key: 'A', option_text: '네, 말씀하세요 (ne, mal-sseum-ha-se-yo)' },
    { question_id: 133, option_key: 'B', option_text: '여기는 경복궁이에요 (yeo-gi-neun gyeong-bok-gung-i-e-yo)' },
    { question_id: 133, option_key: 'C', option_text: '이 카메라예요 (i ka-me-ra-ye-yo)' },
    { question_id: 133, option_key: 'D', option_text: '저 비행기예요 (jeo bi-haeng-gi-ye-yo)' },
    { question_id: 134, option_key: 'A', option_text: '여기 어디예요? (yeo-gi neun eo-di-ye-yo?)' },
    { question_id: 134, option_key: 'B', option_text: '네, 말씀하세요 (ne, mal-sseum-ha-se-yo)' },
    { question_id: 134, option_key: 'C', option_text: '그 가방이에요 (geu ga-bang-i-e-yo)' },
    { question_id: 134, option_key: 'D', option_text: '저 비행기예요 (jeo bi-haeng-gi-ye-yo)' },
    { question_id: 135, option_key: 'A', option_text: 'menjawab tempat ini adalah Gyeongbokgung' },
    { question_id: 135, option_key: 'B', option_text: 'menanyakan izin bertanya' },
    { question_id: 135, option_key: 'C', option_text: 'menyebut benda dekat pembicara' },
    { question_id: 135, option_key: 'D', option_text: 'menunjukkan pesawat jauh' },
    { question_id: 136, option_key: 'A', option_text: 'dekat pembicara' },
    { question_id: 136, option_key: 'B', option_text: 'dekat pendengar' },
    { question_id: 136, option_key: 'C', option_text: 'jauh' },
    { question_id: 136, option_key: 'D', option_text: 'tidak terlihat' },
    { question_id: 137, option_key: 'A', option_text: 'dekat pembicara' },
    { question_id: 137, option_key: 'B', option_text: 'dekat pendengar' },
    { question_id: 137, option_key: 'C', option_text: 'jauh' },
    { question_id: 137, option_key: 'D', option_text: 'berupa tempat' },
    { question_id: 138, option_key: 'A', option_text: 'dekat pembicara' },
    { question_id: 138, option_key: 'B', option_text: 'dekat pendengar' },
    { question_id: 138, option_key: 'C', option_text: 'jauh' },
    { question_id: 138, option_key: 'D', option_text: 'berupa nama orang' },
    { question_id: 139, option_key: 'A', option_text: 'tas ini' },
    { question_id: 139, option_key: 'B', option_text: 'kamera itu' },
    { question_id: 139, option_key: 'C', option_text: 'pesawat itu jauh' },
    { question_id: 139, option_key: 'D', option_text: 'tempat ini' },
    { question_id: 140, option_key: 'A', option_text: '그 가방 (geu ga-bang)' },
    { question_id: 140, option_key: 'B', option_text: '저 비행기 (jeo bi-haeng-gi)' },
    { question_id: 140, option_key: 'C', option_text: '이 가방 (i ga-bang)' },
    { question_id: 140, option_key: 'D', option_text: '그 카메라 (geu ka-me-ra)' },
    { question_id: 141, option_key: 'A', option_text: 'kamera ini' },
    { question_id: 141, option_key: 'B', option_text: 'kamera itu' },
    { question_id: 141, option_key: 'C', option_text: 'pesawat itu' },
    { question_id: 141, option_key: 'D', option_text: 'tas ini' },
    { question_id: 142, option_key: 'A', option_text: '이 카메라 (i ka-me-ra)' },
    { question_id: 142, option_key: 'B', option_text: '저 카메라 (jeo ka-me-ra)' },
    { question_id: 142, option_key: 'C', option_text: '그 카메라 (geu ka-me-ra)' },
    { question_id: 142, option_key: 'D', option_text: '이 비행기 (i bi-haeng-gi)' },
    { question_id: 143, option_key: 'A', option_text: 'pesawat ini' },
    { question_id: 143, option_key: 'B', option_text: 'pesawat itu jauh' },
    { question_id: 143, option_key: 'C', option_text: 'kamera itu' },
    { question_id: 143, option_key: 'D', option_text: 'tas itu' },
    { question_id: 144, option_key: 'A', option_text: '이 비행기 (i bi-haeng-gi)' },
    { question_id: 144, option_key: 'B', option_text: '그 비행기 (geu bi-haeng-gi)' },
    { question_id: 144, option_key: 'C', option_text: '저 비행기 (jeo bi-haeng-gi)' },
    { question_id: 144, option_key: 'D', option_text: '여기 비행기 (yeo-gi bi-haeng-gi)' },
    { question_id: 145, option_key: 'A', option_text: '이 = dekat pendengar' },
    { question_id: 145, option_key: 'B', option_text: '그 = dekat pembicara' },
    { question_id: 145, option_key: 'C', option_text: '저 = jauh' },
    { question_id: 145, option_key: 'D', option_text: '여기 = benda' },
    { question_id: 146, option_key: 'A', option_text: 'benda dekat pembicara' },
    { question_id: 146, option_key: 'B', option_text: 'benda dekat pendengar' },
    { question_id: 146, option_key: 'C', option_text: 'benda jauh' },
    { question_id: 146, option_key: 'D', option_text: 'tempat wisata' },
    { question_id: 147, option_key: 'A', option_text: 'benda dekat pembicara' },
    { question_id: 147, option_key: 'B', option_text: 'benda dekat pendengar' },
    { question_id: 147, option_key: 'C', option_text: 'benda jauh' },
    { question_id: 147, option_key: 'D', option_text: 'nama tempat' },
    { question_id: 148, option_key: 'A', option_text: 'benda dekat pembicara' },
    { question_id: 148, option_key: 'B', option_text: 'benda dekat pendengar' },
    { question_id: 148, option_key: 'C', option_text: 'benda jauh' },
    { question_id: 148, option_key: 'D', option_text: 'benda kecil' },
    { question_id: 149, option_key: 'A', option_text: '그 가방 (geu ga-bang)' },
    { question_id: 149, option_key: 'B', option_text: '이 가방 (i ga-bang)' },
    { question_id: 149, option_key: 'C', option_text: '저 가방 (jeo ga-bang)' },
    { question_id: 149, option_key: 'D', option_text: '여기 가방 (yeo-gi ga-bang)' },
    { question_id: 150, option_key: 'A', option_text: '이 비행기 (i bi-haeng-gi)' },
    { question_id: 150, option_key: 'B', option_text: '그 비행기 (geu bi-haeng-gi)' },
    { question_id: 150, option_key: 'C', option_text: '저 비행기 (jeo bi-haeng-gi)' },
    { question_id: 150, option_key: 'D', option_text: '여기 비행기 (yeo-gi bi-haeng-gi)' },
    { question_id: 151, option_key: 'A', option_text: 'jauh' },
    { question_id: 151, option_key: 'B', option_text: 'dekat pembicara' },
    { question_id: 151, option_key: 'C', option_text: 'dekat pendengar' },
    { question_id: 151, option_key: 'D', option_text: 'tidak diketahui' },
    { question_id: 152, option_key: 'A', option_text: 'dekat pembicara' },
    { question_id: 152, option_key: 'B', option_text: 'jauh sekali' },
    { question_id: 152, option_key: 'C', option_text: 'dekat pendengar' },
    { question_id: 152, option_key: 'D', option_text: 'nama tempat' },
    { question_id: 153, option_key: 'A', option_text: 'dekat pembicara' },
    { question_id: 153, option_key: 'B', option_text: 'dekat pendengar' },
    { question_id: 153, option_key: 'C', option_text: 'di sini' },
    { question_id: 153, option_key: 'D', option_text: 'di sana/jauh' },
    { question_id: 154, option_key: 'A', option_text: '여기 (yeo-gi)' },
    { question_id: 154, option_key: 'B', option_text: '거기 (geo-gi)' },
    { question_id: 154, option_key: 'C', option_text: '저기 (jeo-gi)' },
    { question_id: 154, option_key: 'D', option_text: '어디 (eo-di)' },
    { question_id: 155, option_key: 'A', option_text: '저기 (jeo-gi)' },
    { question_id: 155, option_key: 'B', option_text: '여기 (yeo-gi)' },
    { question_id: 155, option_key: 'C', option_text: '거기 (geo-gi)' },
    { question_id: 155, option_key: 'D', option_text: '어디 (eo-di)' },
    { question_id: 156, option_key: 'A', option_text: '거기 (geo-gi)' },
    { question_id: 156, option_key: 'B', option_text: '저기 (jeo-gi)' },
    { question_id: 156, option_key: 'C', option_text: '여기 (yeo-gi)' },
    { question_id: 156, option_key: 'D', option_text: '어디 (eo-di)' },
    { question_id: 157, option_key: 'A', option_text: 'Ini tempat apa?' },
    { question_id: 157, option_key: 'B', option_text: 'Itu tempat apa?' },
    { question_id: 157, option_key: 'C', option_text: 'Di sana apa?' },
    { question_id: 157, option_key: 'D', option_text: 'Ini benda apa?' },
    { question_id: 158, option_key: 'A', option_text: '거기는 어디예요? (geo-gi-neun eo-di-ye-yo?)' },
    { question_id: 158, option_key: 'B', option_text: '저기는 어디예요? (jeo-gi-neun eo-di-ye-yo?)' },
    { question_id: 158, option_key: 'C', option_text: '여기는 어디예요? (yeo-gi-neun eo-di-ye-yo?)' },
    { question_id: 158, option_key: 'D', option_text: '어디는 여기예요? (eo-di-neun yeo-gi-ye-yo?)' },
    { question_id: 159, option_key: 'A', option_text: '저기는 어디예요? (jeo-gi-neun eo-di-ye-yo?)' },
    { question_id: 159, option_key: 'B', option_text: '여기는 어디예요? (yeo-gi-neun eo-di-ye-yo?)' },
    { question_id: 159, option_key: 'C', option_text: '거기는 어디예요? (geo-gi-neun eo-di-ye-yo?)' },
    { question_id: 159, option_key: 'D', option_text: '여기는 저기예요 (yeo-gi-neun jeo-gi-ye-yo)' },
    { question_id: 160, option_key: 'A', option_text: '여기 (yeo-gi)' },
    { question_id: 160, option_key: 'B', option_text: '어디 (eo-di)' },
    { question_id: 160, option_key: 'C', option_text: '저기 (jeo-gi)' },
    { question_id: 160, option_key: 'D', option_text: '거기 (geo-gi)' },
    { question_id: 161, option_key: 'A', option_text: '저기 (jeo-gi)' },
    { question_id: 161, option_key: 'B', option_text: '여기 (yeo-gi)' },
    { question_id: 161, option_key: 'C', option_text: '거기 (geo-gi)' },
    { question_id: 161, option_key: 'D', option_text: '어디 (eo-di)' },
    { question_id: 162, option_key: 'A', option_text: 'di sini' },
    { question_id: 162, option_key: 'B', option_text: 'di situ' },
    { question_id: 162, option_key: 'C', option_text: 'di mana' },
    { question_id: 162, option_key: 'D', option_text: 'di sana' },
    { question_id: 163, option_key: 'A', option_text: '여기 = di sana' },
    { question_id: 163, option_key: 'B', option_text: '거기 = di sini' },
    { question_id: 163, option_key: 'C', option_text: '저기 = di situ' },
    { question_id: 163, option_key: 'D', option_text: '어디 = di mana' },
    { question_id: 164, option_key: 'A', option_text: '여기 = dekat pembicara' },
    { question_id: 164, option_key: 'B', option_text: '거기 = jauh' },
    { question_id: 164, option_key: 'C', option_text: '저기 = dekat pendengar' },
    { question_id: 164, option_key: 'D', option_text: '어디 = nama tempat' },
    { question_id: 165, option_key: 'A', option_text: 'dekat pembicara' },
    { question_id: 165, option_key: 'B', option_text: 'dekat pendengar' },
    { question_id: 165, option_key: 'C', option_text: 'sangat jauh' },
    { question_id: 165, option_key: 'D', option_text: 'berupa benda' },
    { question_id: 166, option_key: 'A', option_text: 'arah sini' },
    { question_id: 166, option_key: 'B', option_text: 'arah situ' },
    { question_id: 166, option_key: 'C', option_text: 'arah sana' },
    { question_id: 166, option_key: 'D', option_text: 'tempat apa' },
    { question_id: 167, option_key: 'A', option_text: 'arah sini' },
    { question_id: 167, option_key: 'B', option_text: 'arah situ' },
    { question_id: 167, option_key: 'C', option_text: 'arah sana' },
    { question_id: 167, option_key: 'D', option_text: 'di mana' },
    { question_id: 168, option_key: 'A', option_text: 'arah sini' },
    { question_id: 168, option_key: 'B', option_text: 'arah situ' },
    { question_id: 168, option_key: 'C', option_text: 'arah sana' },
    { question_id: 168, option_key: 'D', option_text: 'di sini' },
    { question_id: 169, option_key: 'A', option_text: '그쪽 (geu-jjok)' },
    { question_id: 169, option_key: 'B', option_text: '저쪽 (jeo-jjok)' },
    { question_id: 169, option_key: 'C', option_text: '여기 (yeo-gi)' },
    { question_id: 169, option_key: 'D', option_text: '이쪽 (i-jjok)' },
    { question_id: 170, option_key: 'A', option_text: '그쪽 (geu-jjok)' },
    { question_id: 170, option_key: 'B', option_text: '이쪽 (i-jjok)' },
    { question_id: 170, option_key: 'C', option_text: '저쪽 (jeo-jjok)' },
    { question_id: 170, option_key: 'D', option_text: '어디 (eo-di)' },
    { question_id: 171, option_key: 'A', option_text: '여기 (yeo-gi)' },
    { question_id: 171, option_key: 'B', option_text: '저쪽 (jeo-jjok)' },
    { question_id: 171, option_key: 'C', option_text: '그쪽 (geu-jjok)' },
    { question_id: 171, option_key: 'D', option_text: '이쪽 (i-jjok)' },
    { question_id: 172, option_key: 'A', option_text: 'Ini toilet' },
    { question_id: 172, option_key: 'B', option_text: 'Toilet ada di mana?' },
    { question_id: 172, option_key: 'C', option_text: 'Ini arah sini' },
    { question_id: 172, option_key: 'D', option_text: 'Di sini toilet' },
    { question_id: 173, option_key: 'A', option_text: 'Di arah sana' },
    { question_id: 173, option_key: 'B', option_text: 'Di arah sini' },
    { question_id: 173, option_key: 'C', option_text: 'Di situ' },
    { question_id: 173, option_key: 'D', option_text: 'Di sini' },
    { question_id: 174, option_key: 'A', option_text: '여기는 어디예요? (yeo-gi-neun eo-di-ye-yo?)' },
    { question_id: 174, option_key: 'B', option_text: '어디예요? (eo-di-ye-yo?)' },
    { question_id: 174, option_key: 'C', option_text: '저쪽이에요 (jeo-jjok-i-e-yo)' },
    { question_id: 174, option_key: 'D', option_text: '거기 (geo-gi)' },
    { question_id: 175, option_key: 'A', option_text: '이쪽이에요 (i-jjok-i-e-yo)' },
    { question_id: 175, option_key: 'B', option_text: '그쪽이에요 (geu-jjok-i-e-yo)' },
    { question_id: 175, option_key: 'C', option_text: '여기는 어디예요? (yeo-gi-neun eo-di-ye-yo?)' },
    { question_id: 175, option_key: 'D', option_text: '저쪽이에요 (jeo-jjok-i-e-yo)' },
    { question_id: 176, option_key: 'A', option_text: 'toilet' },
    { question_id: 176, option_key: 'B', option_text: 'bandara' },
    { question_id: 176, option_key: 'C', option_text: 'paspor' },
    { question_id: 176, option_key: 'D', option_text: 'kamera' },
    { question_id: 177, option_key: 'A', option_text: 'nama benda' },
    { question_id: 177, option_key: 'B', option_text: 'arah/lokasi' },
    { question_id: 177, option_key: 'C', option_text: 'profesi' },
    { question_id: 177, option_key: 'D', option_text: 'sapaan' },
    { question_id: 178, option_key: 'A', option_text: '이쪽 = arah sana' },
    { question_id: 178, option_key: 'B', option_text: '그쪽 = arah sini' },
    { question_id: 178, option_key: 'C', option_text: '저쪽 = arah sana' },
    { question_id: 178, option_key: 'D', option_text: '어디 = arah situ' },
    { question_id: 179, option_key: 'A', option_text: '저쪽 (jeo-jjok)' },
    { question_id: 179, option_key: 'B', option_text: '어디 (eo-di)' },
    { question_id: 179, option_key: 'C', option_text: '그쪽 (geu-jjok)' },
    { question_id: 179, option_key: 'D', option_text: '이쪽 (i-jjok)' },
    { question_id: 180, option_key: 'A', option_text: '저쪽이에요 → 화장실이 어디예요?' },
    { question_id: 180, option_key: 'B', option_text: '화장실이 어디예요? → 저쪽이에요' },
    { question_id: 180, option_key: 'C', option_text: '여기는 어디예요? → 이쪽' },
    { question_id: 180, option_key: 'D', option_text: '그쪽 → 화장실이 어디예요?' },
    { question_id: 181, option_key: 'A', option_text: 'berada di suatu tempat' },
    { question_id: 181, option_key: 'B', option_text: 'pergi ke suatu tempat' },
    { question_id: 181, option_key: 'C', option_text: 'benda dekat pembicara' },
    { question_id: 181, option_key: 'D', option_text: 'arah sana' },
    { question_id: 182, option_key: 'A', option_text: 'Ada di mana?' },
    { question_id: 182, option_key: 'B', option_text: 'Ini apa?' },
    { question_id: 182, option_key: 'C', option_text: 'Pergi ke mana?' },
    { question_id: 182, option_key: 'D', option_text: 'Di sini apa?' },
    { question_id: 183, option_key: 'A', option_text: '가방이 어디에 있어요? (ga-bang-i eo-di-e i-sseo-yo?)' },
    { question_id: 183, option_key: 'B', option_text: '어디 가요? (eo-di ga-yo?)' },
    { question_id: 183, option_key: 'C', option_text: '편의점에 가요 (pyeon-ui-jeom-e ga-yo)' },
    { question_id: 183, option_key: 'D', option_text: '책상 앞에 있어요 (chaek-sang ap-e i-sseo-yo)' },
    { question_id: 184, option_key: 'A', option_text: 'Ada di depan meja' },
    { question_id: 184, option_key: 'B', option_text: 'Tas ada di mana?' },
    { question_id: 184, option_key: 'C', option_text: 'Pergi ke minimarket' },
    { question_id: 184, option_key: 'D', option_text: 'Di sini' },
    { question_id: 185, option_key: 'A', option_text: '가방이 어디에 있어요? (ga-bang-i eo-di-e i-sseo-yo?)' },
    { question_id: 185, option_key: 'B', option_text: '편의점에 가요 (pyeon-ui-jeom-e ga-yo)' },
    { question_id: 185, option_key: 'C', option_text: '-에 있어요 (-e i-sseo-yo)' },
    { question_id: 185, option_key: 'D', option_text: '책상 앞에 있어요 (chaek-sang ap-e i-sseo-yo)' },
    { question_id: 186, option_key: 'A', option_text: '편의점에 가요 (pyeon-ui-jeom-e ga-yo)' },
    { question_id: 186, option_key: 'B', option_text: '어디 가요? (eo-di ga-yo?)' },
    { question_id: 186, option_key: 'C', option_text: '가방이 어디에 있어요? (ga-bang-i eo-di-e i-sseo-yo?)' },
    { question_id: 186, option_key: 'D', option_text: '가방이 책상 앞에 있어요 (ga-bang-i chaek-sang ap-e i-sseo-yo)' },
    { question_id: 187, option_key: 'A', option_text: 'pergi ke' },
    { question_id: 187, option_key: 'B', option_text: 'berada di' },
    { question_id: 187, option_key: 'C', option_text: 'di depan' },
    { question_id: 187, option_key: 'D', option_text: 'tas' },
    { question_id: 188, option_key: 'A', option_text: 'lokasi benda' },
    { question_id: 188, option_key: 'B', option_text: 'tujuan pergi' },
    { question_id: 188, option_key: 'C', option_text: 'posisi tas' },
    { question_id: 188, option_key: 'D', option_text: 'benda di meja' },
    { question_id: 189, option_key: 'A', option_text: '어디 가요? (eo-di ga-yo?) → 편의점에 가요 (pyeon-ui-jeom-e ga-yo)' },
    { question_id: 189, option_key: 'B', option_text: '어디 가요? (eo-di ga-yo?) → 가방이 어디에 있어요? (ga-bang-i eo-di-e i-sseo-yo?)' },
    { question_id: 189, option_key: 'C', option_text: '편의점에 가요 (pyeon-ui-jeom-e ga-yo) → 어디 가요? (eo-di ga-yo?)' },
    { question_id: 189, option_key: 'D', option_text: '가방이 책상 앞에 있어요 (ga-bang-i chaek-sang ap-e i-sseo-yo) → 어디 가요? (eo-di ga-yo?)' },
    { question_id: 190, option_key: 'A', option_text: 'tujuan pergi' },
    { question_id: 190, option_key: 'B', option_text: 'letak tas' },
    { question_id: 190, option_key: 'C', option_text: 'benda dekat pembicara' },
    { question_id: 190, option_key: 'D', option_text: 'posisi di depan meja' },
    { question_id: 191, option_key: 'A', option_text: '가방이 어디에 있어요? (ga-bang-i eo-di-e i-sseo-yo?)' },
    { question_id: 191, option_key: 'B', option_text: '어디 가요? (eo-di ga-yo?)' },
    { question_id: 191, option_key: 'C', option_text: '여기는 어디예요? (yeo-gi-neun eo-di-ye-yo?)' },
    { question_id: 191, option_key: 'D', option_text: '이게 뭐예요? (i-ge mwo-ye-yo?)' },
    { question_id: 192, option_key: 'A', option_text: 'di mana / ke mana' },
    { question_id: 192, option_key: 'B', option_text: 'tas' },
    { question_id: 192, option_key: 'C', option_text: 'meja' },
    { question_id: 192, option_key: 'D', option_text: 'minimarket' },
    { question_id: 193, option_key: 'A', option_text: 'bertanya nama' },
    { question_id: 193, option_key: 'B', option_text: 'pergi' },
    { question_id: 193, option_key: 'C', option_text: 'berada' },
    { question_id: 193, option_key: 'D', option_text: 'menunjukkan benda' },
    { question_id: 194, option_key: 'A', option_text: '편의점에 가요 (pyeon-ui-jeom-e ga-yo)' },
    { question_id: 194, option_key: 'B', option_text: '가방이 어디에 있어요? (ga-bang-i eo-di-e i-sseo-yo?)' },
    { question_id: 194, option_key: 'C', option_text: '책상 앞에 있어요 (chaek-sang ap-e i-sseo-yo)' },
    { question_id: 194, option_key: 'D', option_text: '가방이 책상 앞에 있어요 (ga-bang-i chaek-sang ap-e i-sseo-yo)' },
    { question_id: 195, option_key: 'A', option_text: 'seseorang sedang menuju minimarket' },
    { question_id: 195, option_key: 'B', option_text: 'tas berada di depan meja' },
    { question_id: 195, option_key: 'C', option_text: 'seseorang bertanya lokasi tas' },
    { question_id: 195, option_key: 'D', option_text: 'meja berada di depan tas' },
    { question_id: 196, option_key: 'A', option_text: 'pergi ke tempat' },
    { question_id: 196, option_key: 'B', option_text: 'berada di tempat' },
    { question_id: 196, option_key: 'C', option_text: 'bertanya tujuan pergi' },
    { question_id: 196, option_key: 'D', option_text: 'menyapa orang' },
    { question_id: 197, option_key: 'A', option_text: 'Tas ada di mana?' },
    { question_id: 197, option_key: 'B', option_text: 'Pergi ke mana?' },
    { question_id: 197, option_key: 'C', option_text: 'Tas pergi ke mana?' },
    { question_id: 197, option_key: 'D', option_text: 'Ini minimarket' },
    { question_id: 198, option_key: 'A', option_text: '어디 가요? (eo-di ga-yo?)' },
    { question_id: 198, option_key: 'B', option_text: '편의점에 가요 (pyeon-ui-jeom-e ga-yo)' },
    { question_id: 198, option_key: 'C', option_text: '가방이 어디에 있어요? (ga-bang-i eo-di-e i-sseo-yo?)' },
    { question_id: 198, option_key: 'D', option_text: '책상 앞에 있어요 (chaek-sang ap-e i-sseo-yo)' },
    { question_id: 199, option_key: 'A', option_text: 'Tas ada di depan meja' },
    { question_id: 199, option_key: 'B', option_text: 'Pergi ke minimarket' },
    { question_id: 199, option_key: 'C', option_text: 'Pergi ke mana?' },
    { question_id: 199, option_key: 'D', option_text: 'Tas ada di mana?' },
    { question_id: 200, option_key: 'A', option_text: '어디 가요? (eo-di ga-yo?)' },
    { question_id: 200, option_key: 'B', option_text: '편의점에 가요 (pyeon-ui-jeom-e ga-yo)' },
    { question_id: 200, option_key: 'C', option_text: '가방이 책상 앞에 있어요 (ga-bang-i chaek-sang ap-e i-sseo-yo)' },
    { question_id: 200, option_key: 'D', option_text: '-에 가요 (-e ga-yo)' },
    { question_id: 201, option_key: 'A', option_text: 'meja' },
    { question_id: 201, option_key: 'B', option_text: 'tas' },
    { question_id: 201, option_key: 'C', option_text: 'minimarket' },
    { question_id: 201, option_key: 'D', option_text: 'tempat' },
    { question_id: 202, option_key: 'A', option_text: 'depan meja' },
    { question_id: 202, option_key: 'B', option_text: 'di mana' },
    { question_id: 202, option_key: 'C', option_text: 'minimarket' },
    { question_id: 202, option_key: 'D', option_text: 'pergi ke' },
    { question_id: 203, option_key: 'A', option_text: '어디 가요? (eo-di ga-yo?)' },
    { question_id: 203, option_key: 'B', option_text: '편의점에 가요 (pyeon-ui-jeom-e ga-yo)' },
    { question_id: 203, option_key: 'C', option_text: '가방이 책상 앞에 있어요 (ga-bang-i chaek-sang ap-e i-sseo-yo)' },
    { question_id: 203, option_key: 'D', option_text: '어디 가요? → 편의점에 가요 (eo-di ga-yo? → pyeon-ui-jeom-e ga-yo)' },
    { question_id: 204, option_key: 'A', option_text: 'tujuan pergi' },
    { question_id: 204, option_key: 'B', option_text: 'posisi/keberadaan benda' },
    { question_id: 204, option_key: 'C', option_text: 'sapaan formal' },
    { question_id: 204, option_key: 'D', option_text: 'nama seseorang' },
    { question_id: 205, option_key: 'A', option_text: '-에 가요 untuk pergi ke tempat, -에 있어요 untuk berada di tempat' },
    { question_id: 205, option_key: 'B', option_text: '-에 가요 untuk benda, -에 있어요 untuk nama' },
    { question_id: 205, option_key: 'C', option_text: 'keduanya hanya untuk bertanya nama' },
    { question_id: 205, option_key: 'D', option_text: 'keduanya berarti sama persis' },
    { question_id: 206, option_key: 'A', option_text: '어디 가요? (eo-di ga-yo?)' },
    { question_id: 206, option_key: 'B', option_text: '편의점에 가요 (pyeon-ui-jeom-e ga-yo)' },
    { question_id: 206, option_key: 'C', option_text: '가방이 어디에 있어요? (ga-bang-i eo-di-e i-sseo-yo?)' },
    { question_id: 206, option_key: 'D', option_text: '편의점에 있어요 (pyeon-ui-jeom-e i-sseo-yo)' },
    { question_id: 207, option_key: 'A', option_text: '가방이 책상 앞에 있어요 (ga-bang-i chaek-sang ap-e i-sseo-yo)' },
    { question_id: 207, option_key: 'B', option_text: '가방이 어디에 있어요? (ga-bang-i eo-di-e i-sseo-yo?)' },
    { question_id: 207, option_key: 'C', option_text: '어디 가요? (eo-di ga-yo?)' },
    { question_id: 207, option_key: 'D', option_text: '편의점에 가요 (pyeon-ui-jeom-e ga-yo)' },
    { question_id: 208, option_key: 'A', option_text: 'pergi ke mana' },
    { question_id: 208, option_key: 'B', option_text: 'berada di mana' },
    { question_id: 208, option_key: 'C', option_text: 'siapa nama kamu' },
    { question_id: 208, option_key: 'D', option_text: 'ini apa' },
    { question_id: 209, option_key: 'A', option_text: '어디 가요? → 가방이 책상 앞에 있어요' },
    { question_id: 209, option_key: 'B', option_text: '가방이 어디에 있어요? → 편의점에 가요' },
    { question_id: 209, option_key: 'C', option_text: '가방이 어디에 있어요? → 가방이 책상 앞에 있어요' },
    { question_id: 209, option_key: 'D', option_text: '편의점에 가요 → 어디에 있어요?' },
    { question_id: 210, option_key: 'A', option_text: '가방이 책상 앞에 있어요 → 가방이 어디에 있어요?' },
    { question_id: 210, option_key: 'B', option_text: '가방이 어디에 있어요? → 가방이 책상 앞에 있어요' },
    { question_id: 210, option_key: 'C', option_text: '편의점에 가요 → 어디 가요?' },
    { question_id: 210, option_key: 'D', option_text: '책상 앞에 있어요 → 어디 가요?' },
    { question_id: 211, option_key: 'A', option_text: 'di bawah' },
    { question_id: 211, option_key: 'B', option_text: 'di atas' },
    { question_id: 211, option_key: 'C', option_text: 'di depan' },
    { question_id: 211, option_key: 'D', option_text: 'di belakang' },
    { question_id: 212, option_key: 'A', option_text: '앞 (ap)' },
    { question_id: 212, option_key: 'B', option_text: '뒤 (dwi)' },
    { question_id: 212, option_key: 'C', option_text: '아래 (a-rae)' },
    { question_id: 212, option_key: 'D', option_text: '옆 (yeop)' },
    { question_id: 213, option_key: 'A', option_text: 'di depan' },
    { question_id: 213, option_key: 'B', option_text: 'di belakang' },
    { question_id: 213, option_key: 'C', option_text: 'di samping' },
    { question_id: 213, option_key: 'D', option_text: 'di antara' },
    { question_id: 214, option_key: 'A', option_text: '안 (an)' },
    { question_id: 214, option_key: 'B', option_text: '밖 (bak)' },
    { question_id: 214, option_key: 'C', option_text: '위 (wi)' },
    { question_id: 214, option_key: 'D', option_text: '뒤 (dwi)' },
    { question_id: 215, option_key: 'A', option_text: 'di atas' },
    { question_id: 215, option_key: 'B', option_text: 'di samping' },
    { question_id: 215, option_key: 'C', option_text: 'di luar' },
    { question_id: 215, option_key: 'D', option_text: 'di antara' },
    { question_id: 216, option_key: 'A', option_text: '사이 (sa-i)' },
    { question_id: 216, option_key: 'B', option_text: '안 (an)' },
    { question_id: 216, option_key: 'C', option_text: '앞 (ap)' },
    { question_id: 216, option_key: 'D', option_text: '아래 (a-rae)' },
    { question_id: 217, option_key: 'A', option_text: 'di luar' },
    { question_id: 217, option_key: 'B', option_text: 'di depan' },
    { question_id: 217, option_key: 'C', option_text: 'di dalam' },
    { question_id: 217, option_key: 'D', option_text: 'di belakang' },
    { question_id: 218, option_key: 'A', option_text: '위 (wi)' },
    { question_id: 218, option_key: 'B', option_text: '옆 (yeop)' },
    { question_id: 218, option_key: 'C', option_text: '사이 (sa-i)' },
    { question_id: 218, option_key: 'D', option_text: '밖 (bak)' },
    { question_id: 219, option_key: 'A', option_text: '위 (wi) = di bawah' },
    { question_id: 219, option_key: 'B', option_text: '아래 (a-rae) = di atas' },
    { question_id: 219, option_key: 'C', option_text: '앞 (ap) = di depan' },
    { question_id: 219, option_key: 'D', option_text: '뒤 (dwi) = di dalam' },
    { question_id: 220, option_key: 'A', option_text: '위 (wi) dan 아래 (a-rae)' },
    { question_id: 220, option_key: 'B', option_text: '앞 (ap) dan 옆 (yeop)' },
    { question_id: 220, option_key: 'C', option_text: '안 (an) dan 사이 (sa-i)' },
    { question_id: 220, option_key: 'D', option_text: '밖 (bak) dan 뒤 (dwi)' },
    { question_id: 221, option_key: 'A', option_text: '앞 (ap) dan 뒤 (dwi)' },
    { question_id: 221, option_key: 'B', option_text: '안 (an) dan 밖 (bak)' },
    { question_id: 221, option_key: 'C', option_text: '위 (wi) dan 옆 (yeop)' },
    { question_id: 221, option_key: 'D', option_text: '아래 (a-rae) dan 사이 (sa-i)' },
    { question_id: 222, option_key: 'A', option_text: '사이 (sa-i)' },
    { question_id: 222, option_key: 'B', option_text: '뒤 (dwi)' },
    { question_id: 222, option_key: 'C', option_text: '옆 (yeop)' },
    { question_id: 222, option_key: 'D', option_text: '위 (wi)' },
    { question_id: 223, option_key: 'A', option_text: '밖 (bak)' },
    { question_id: 223, option_key: 'B', option_text: '사이 (sa-i)' },
    { question_id: 223, option_key: 'C', option_text: '안 (an)' },
    { question_id: 223, option_key: 'D', option_text: '앞 (ap)' },
    { question_id: 224, option_key: 'A', option_text: '앞 (ap)' },
    { question_id: 224, option_key: 'B', option_text: '위 (wi)' },
    { question_id: 224, option_key: 'C', option_text: '아래 (a-rae)' },
    { question_id: 224, option_key: 'D', option_text: '밖 (bak)' },
    { question_id: 225, option_key: 'A', option_text: '위 (wi)' },
    { question_id: 225, option_key: 'B', option_text: '옆 (yeop)' },
    { question_id: 225, option_key: 'C', option_text: '안 (an)' },
    { question_id: 225, option_key: 'D', option_text: '사이 (sa-i)' },
    { question_id: 226, option_key: 'A', option_text: 'Ada di mana?' },
    { question_id: 226, option_key: 'B', option_text: 'Ini apa?' },
    { question_id: 226, option_key: 'C', option_text: 'Pergi ke sana naik apa?' },
    { question_id: 226, option_key: 'D', option_text: 'Di atas apa?' },
    { question_id: 227, option_key: 'A', option_text: '어떻게 가요? (eo-tteo-ke ga-yo?)' },
    { question_id: 227, option_key: 'B', option_text: '어디 가요? (eo-di ga-yo?)' },
    { question_id: 227, option_key: 'C', option_text: '어디예요? (eo-di-ye-yo?)' },
    { question_id: 227, option_key: 'D', option_text: '저쪽이에요 (jeo-jjok-i-e-yo)' },
    { question_id: 228, option_key: 'A', option_text: 'Gyeongbokgung ada di mana?' },
    { question_id: 228, option_key: 'B', option_text: 'Ke Gyeongbokgung naik apa?' },
    { question_id: 228, option_key: 'C', option_text: 'Ini Gyeongbokgung' },
    { question_id: 228, option_key: 'D', option_text: 'Gyeongbokgung di sana' },
    { question_id: 229, option_key: 'A', option_text: '경복궁에 어떻게 가요? (gyeong-bok-gung-e eo-tteo-ke ga-yo?)' },
    { question_id: 229, option_key: 'B', option_text: '경복궁이에요 (gyeong-bok-gung-i-e-yo)' },
    { question_id: 229, option_key: 'C', option_text: '여기는 경복궁이에요 (yeo-gi-neun gyeong-bok-gung-i-e-yo)' },
    { question_id: 229, option_key: 'D', option_text: '경복궁 어디예요? (gyeong-bok-gung eo-di-ye-yo?)' },
    { question_id: 230, option_key: 'A', option_text: 'cara' },
    { question_id: 230, option_key: 'B', option_text: 'nama' },
    { question_id: 230, option_key: 'C', option_text: 'benda' },
    { question_id: 230, option_key: 'D', option_text: 'posisi' },
    { question_id: 231, option_key: 'A', option_text: 'berada' },
    { question_id: 231, option_key: 'B', option_text: 'pergi' },
    { question_id: 231, option_key: 'C', option_text: 'bertanya nama' },
    { question_id: 231, option_key: 'D', option_text: 'menunjukkan posisi' },
    { question_id: 232, option_key: 'A', option_text: 'cara menuju suatu tempat' },
    { question_id: 232, option_key: 'B', option_text: 'arti sebuah benda' },
    { question_id: 232, option_key: 'C', option_text: 'posisi di atas' },
    { question_id: 232, option_key: 'D', option_text: 'nama seseorang' },
    { question_id: 233, option_key: 'A', option_text: '어떻게 가요? (eo-tteo-ke ga-yo?)' },
    { question_id: 233, option_key: 'B', option_text: '경복궁에 어떻게 가요? (gyeong-bok-gung-e eo-tteo-ke ga-yo?)' },
    { question_id: 233, option_key: 'C', option_text: '경복궁이에요 (gyeong-bok-gung-i-e-yo)' },
    { question_id: 233, option_key: 'D', option_text: '어디예요? (eo-di-ye-yo?)' },
    { question_id: 234, option_key: 'A', option_text: 'tujuan tempat' },
    { question_id: 234, option_key: 'B', option_text: 'posisi benda' },
    { question_id: 234, option_key: 'C', option_text: 'sapaan' },
    { question_id: 234, option_key: 'D', option_text: 'profesi' },
    { question_id: 235, option_key: 'A', option_text: '어디 가요? menanyakan tujuan, 어떻게 가요? menanyakan cara pergi' },
    { question_id: 235, option_key: 'B', option_text: 'keduanya berarti “di mana?”' },
    { question_id: 235, option_key: 'C', option_text: '어디 가요? untuk posisi, 어떻게 가요? untuk nama' },
    { question_id: 235, option_key: 'D', option_text: 'keduanya berarti “ini apa?”' },
    { question_id: 236, option_key: 'A', option_text: '어떻게 가요? (eo-tteo-ke ga-yo?)' },
    { question_id: 236, option_key: 'B', option_text: '위예요 (wi-ye-yo)' },
    { question_id: 236, option_key: 'C', option_text: '안이에요 (an-i-e-yo)' },
    { question_id: 236, option_key: 'D', option_text: '밖이에요 (bak-i-e-yo)' },
    { question_id: 237, option_key: 'A', option_text: '어떻게 가요? (eo-tteo-ke ga-yo?) = Pergi ke sana naik apa?' },
    { question_id: 237, option_key: 'B', option_text: '경복궁에 어떻게 가요? (gyeong-bok-gung-e eo-tteo-ke ga-yo?) = Ini Gyeongbokgung' },
    { question_id: 237, option_key: 'C', option_text: '위 (wi) = di bawah' },
    { question_id: 237, option_key: 'D', option_text: '밖 (bak) = di dalam' },
    { question_id: 238, option_key: 'A', option_text: 'ingin bertanya cara menuju Gyeongbokgung' },
    { question_id: 238, option_key: 'B', option_text: 'ingin mengatakan benda ada di atas' },
    { question_id: 238, option_key: 'C', option_text: 'ingin bertanya nama seseorang' },
    { question_id: 238, option_key: 'D', option_text: 'ingin mengatakan berada di dalam' },
    { question_id: 239, option_key: 'A', option_text: 'posisi benda' },
    { question_id: 239, option_key: 'B', option_text: 'cara menuju tempat' },
    { question_id: 239, option_key: 'C', option_text: 'arti profesi' },
    { question_id: 239, option_key: 'D', option_text: 'sapaan sosial' },
    { question_id: 240, option_key: 'A', option_text: '경복궁에 어떻게 가요? (gyeong-bok-gung-e eo-tteo-ke ga-yo?)' },
    { question_id: 240, option_key: 'B', option_text: '경복궁에 어디예요? (gyeong-bok-gung-e eo-di-ye-yo?)' },
    { question_id: 240, option_key: 'C', option_text: '어떻게 경복궁이에요? (eo-tteo-ke gyeong-bok-gung-i-e-yo?)' },
    { question_id: 240, option_key: 'D', option_text: '가요 어떻게 경복궁에? (ga-yo eo-tteo-ke gyeong-bok-gung-e?)' },
    { question_id: 241, option_key: 'A', option_text: 'bus' },
    { question_id: 241, option_key: 'B', option_text: 'subway' },
    { question_id: 241, option_key: 'C', option_text: 'taksi' },
    { question_id: 241, option_key: 'D', option_text: 'kereta' },
    { question_id: 242, option_key: 'A', option_text: '기차 (gi-cha)' },
    { question_id: 242, option_key: 'B', option_text: '택시 (taek-si)' },
    { question_id: 242, option_key: 'C', option_text: '버스 (beo-seu)' },
    { question_id: 242, option_key: 'D', option_text: '자동차 (ja-dong-cha)' },
    { question_id: 243, option_key: 'A', option_text: 'taksi' },
    { question_id: 243, option_key: 'B', option_text: 'kereta' },
    { question_id: 243, option_key: 'C', option_text: 'mobil' },
    { question_id: 243, option_key: 'D', option_text: 'sepeda' },
    { question_id: 244, option_key: 'A', option_text: '비행기 (bi-haeng-gi)' },
    { question_id: 244, option_key: 'B', option_text: '배 (bae)' },
    { question_id: 244, option_key: 'C', option_text: '자동차 (ja-dong-cha)' },
    { question_id: 244, option_key: 'D', option_text: '기차 (gi-cha)' },
    { question_id: 245, option_key: 'A', option_text: 'kapal' },
    { question_id: 245, option_key: 'B', option_text: 'mobil' },
    { question_id: 245, option_key: 'C', option_text: 'subway' },
    { question_id: 245, option_key: 'D', option_text: 'bus' },
    { question_id: 246, option_key: 'A', option_text: '버스 (beo-seu)' },
    { question_id: 246, option_key: 'B', option_text: '기차 (gi-cha)' },
    { question_id: 246, option_key: 'C', option_text: '자전거 (ja-jeon-geo)' },
    { question_id: 246, option_key: 'D', option_text: '택시 (taek-si)' },
    { question_id: 247, option_key: 'A', option_text: 'pesawat' },
    { question_id: 247, option_key: 'B', option_text: 'kapal' },
    { question_id: 247, option_key: 'C', option_text: 'mobil' },
    { question_id: 247, option_key: 'D', option_text: 'kereta' },
    { question_id: 248, option_key: 'A', option_text: '자동차 (ja-dong-cha)' },
    { question_id: 248, option_key: 'B', option_text: '배 (bae)' },
    { question_id: 248, option_key: 'C', option_text: '지하철 (ji-ha-cheol)' },
    { question_id: 248, option_key: 'D', option_text: '자전거 (ja-jeon-geo)' },
    { question_id: 249, option_key: 'A', option_text: '버스 (beo-seu) = taksi' },
    { question_id: 249, option_key: 'B', option_text: '기차 (gi-cha) = kereta' },
    { question_id: 249, option_key: 'C', option_text: '배 (bae) = pesawat' },
    { question_id: 249, option_key: 'D', option_text: '자동차 (ja-dong-cha) = sepeda' },
    { question_id: 250, option_key: 'A', option_text: '비행기 (bi-haeng-gi), 배 (bae)' },
    { question_id: 250, option_key: 'B', option_text: '배 (bae), 지하철 (ji-ha-cheol)' },
    { question_id: 250, option_key: 'C', option_text: '자동차 (ja-dong-cha), 자전거 (ja-jeon-geo)' },
    { question_id: 250, option_key: 'D', option_text: '비행기 (bi-haeng-gi), 기차 (gi-cha)' },
    { question_id: 251, option_key: 'A', option_text: '비행기 (bi-haeng-gi) dan 배 (bae)' },
    { question_id: 251, option_key: 'B', option_text: '택시 (taek-si) dan 버스 (beo-seu)' },
    { question_id: 251, option_key: 'C', option_text: '기차 (gi-cha) dan 지하철 (ji-ha-cheol)' },
    { question_id: 251, option_key: 'D', option_text: '자동차 (ja-dong-cha) dan 자전거 (ja-jeon-geo)' },
    { question_id: 252, option_key: 'A', option_text: '지하철 (ji-ha-cheol)' },
    { question_id: 252, option_key: 'B', option_text: '택시 (taek-si)' },
    { question_id: 252, option_key: 'C', option_text: '배 (bae)' },
    { question_id: 252, option_key: 'D', option_text: '자전거 (ja-jeon-geo)' },
    { question_id: 253, option_key: 'A', option_text: 'subway' },
    { question_id: 253, option_key: 'B', option_text: 'bus' },
    { question_id: 253, option_key: 'C', option_text: 'kereta' },
    { question_id: 253, option_key: 'D', option_text: 'kapal' },
    { question_id: 254, option_key: 'A', option_text: 'mobil' },
    { question_id: 254, option_key: 'B', option_text: 'sepeda' },
    { question_id: 254, option_key: 'C', option_text: 'bus' },
    { question_id: 254, option_key: 'D', option_text: 'taksi' },
    { question_id: 255, option_key: 'A', option_text: '버스 (beo-seu)' },
    { question_id: 255, option_key: 'B', option_text: '택시 (taek-si)' },
    { question_id: 255, option_key: 'C', option_text: '자동차 (ja-dong-cha)' },
    { question_id: 255, option_key: 'D', option_text: '배 (bae)' },
    { question_id: 256, option_key: 'A', option_text: 'pergi menggunakan sesuatu' },
    { question_id: 256, option_key: 'B', option_text: 'berada di suatu tempat' },
    { question_id: 256, option_key: 'C', option_text: 'bertanya lokasi benda' },
    { question_id: 256, option_key: 'D', option_text: 'menyebut nama orang' },
    { question_id: 257, option_key: 'A', option_text: 'Pergi ke restoran naik sepeda' },
    { question_id: 257, option_key: 'B', option_text: 'Pergi ke restoran naik mobil' },
    { question_id: 257, option_key: 'C', option_text: 'Sepeda ada di restoran' },
    { question_id: 257, option_key: 'D', option_text: 'Restoran ada di sana' },
    { question_id: 258, option_key: 'A', option_text: '식당에 자동차로 가요 (sik-dang-e ja-dong-cha-ro ga-yo)' },
    { question_id: 258, option_key: 'B', option_text: '식당에 자전거로 가요 (sik-dang-e ja-jeon-geo-ro ga-yo)' },
    { question_id: 258, option_key: 'C', option_text: '식당에 버스로 가요 (sik-dang-e beo-seu-ro ga-yo)' },
    { question_id: 258, option_key: 'D', option_text: '식당에 택시로 가요 (sik-dang-e taek-si-ro ga-yo)' },
    { question_id: 259, option_key: 'A', option_text: 'tujuan pergi' },
    { question_id: 259, option_key: 'B', option_text: 'alat/transportasi yang digunakan' },
    { question_id: 259, option_key: 'C', option_text: 'lokasi benda' },
    { question_id: 259, option_key: 'D', option_text: 'arah tempat' },
    { question_id: 260, option_key: 'A', option_text: 'pergi' },
    { question_id: 260, option_key: 'B', option_text: 'berada' },
    { question_id: 260, option_key: 'C', option_text: 'bertanya' },
    { question_id: 260, option_key: 'D', option_text: 'melihat' },
    { question_id: 261, option_key: 'A', option_text: '버스로 가요 (beo-seu-ro ga-yo)' },
    { question_id: 261, option_key: 'B', option_text: '버스에 있어요 (beo-seu-e i-sseo-yo)' },
    { question_id: 261, option_key: 'C', option_text: '버스 어디예요 (beo-seu eo-di-ye-yo)' },
    { question_id: 261, option_key: 'D', option_text: '버스이에요 (beo-seu-i-e-yo)' },
    { question_id: 262, option_key: 'A', option_text: '기차로 가요 (gi-cha-ro ga-yo)' },
    { question_id: 262, option_key: 'B', option_text: '택시로 가요 (taek-si-ro ga-yo)' },
    { question_id: 262, option_key: 'C', option_text: '배로 가요 (bae-ro ga-yo)' },
    { question_id: 262, option_key: 'D', option_text: '지하철로 가요 (ji-ha-cheol-ro ga-yo)' },
    { question_id: 263, option_key: 'A', option_text: '자동차로 가요 (ja-dong-cha-ro ga-yo)' },
    { question_id: 263, option_key: 'B', option_text: '버스로 가요 (beo-seu-ro ga-yo)' },
    { question_id: 263, option_key: 'C', option_text: '지하철로 가요 (ji-ha-cheol-ro ga-yo)' },
    { question_id: 263, option_key: 'D', option_text: '자전거로 가요 (ja-jeon-geo-ro ga-yo)' },
    { question_id: 264, option_key: 'A', option_text: '배로 가요 (bae-ro ga-yo)' },
    { question_id: 264, option_key: 'B', option_text: '비행기로 가요 (bi-haeng-gi-ro ga-yo)' },
    { question_id: 264, option_key: 'C', option_text: '택시로 가요 (taek-si-ro ga-yo)' },
    { question_id: 264, option_key: 'D', option_text: '기차로 가요 (gi-cha-ro ga-yo)' },
    { question_id: 265, option_key: 'A', option_text: '비행기로 가요 (bi-haeng-gi-ro ga-yo) = pergi naik kapal' },
    { question_id: 265, option_key: 'B', option_text: '기차로 가요 (gi-cha-ro ga-yo) = pergi naik kereta' },
    { question_id: 265, option_key: 'C', option_text: '자전거로 가요 (ja-jeon-geo-ro ga-yo) = pergi naik bus' },
    { question_id: 265, option_key: 'D', option_text: '택시로 가요 (taek-si-ro ga-yo) = pergi naik mobil' },
    { question_id: 266, option_key: 'A', option_text: 'pergi naik mobil' },
    { question_id: 266, option_key: 'B', option_text: 'pergi naik sepeda' },
    { question_id: 266, option_key: 'C', option_text: 'pergi naik bus' },
    { question_id: 266, option_key: 'D', option_text: 'pergi naik subway' },
    { question_id: 267, option_key: 'A', option_text: 'pergi naik taksi' },
    { question_id: 267, option_key: 'B', option_text: 'pergi naik bus' },
    { question_id: 267, option_key: 'C', option_text: 'pergi naik kapal' },
    { question_id: 267, option_key: 'D', option_text: 'pergi naik pesawat' },
    { question_id: 268, option_key: 'A', option_text: 'pergi naik kereta' },
    { question_id: 268, option_key: 'B', option_text: 'pergi naik mobil' },
    { question_id: 268, option_key: 'C', option_text: 'pergi naik pesawat' },
    { question_id: 268, option_key: 'D', option_text: 'pergi naik sepeda' },
    { question_id: 269, option_key: 'A', option_text: '자전거로 가요 (ja-jeon-geo-ro ga-yo)' },
    { question_id: 269, option_key: 'B', option_text: '자전거예요 (ja-jeon-geo-ye-yo)' },
    { question_id: 269, option_key: 'C', option_text: '자전거가 어디예요 (ja-jeon-geo-ga eo-di-ye-yo)' },
    { question_id: 269, option_key: 'D', option_text: '자전거에 있어요 (ja-jeon-geo-e i-sseo-yo)' },
    { question_id: 270, option_key: 'A', option_text: '택시로 가요 (taek-si-ro ga-yo)' },
    { question_id: 270, option_key: 'B', option_text: '어디 가요? (eo-di ga-yo?)' },
    { question_id: 270, option_key: 'C', option_text: '여기는 어디예요? (yeo-gi-neun eo-di-ye-yo?)' },
    { question_id: 270, option_key: 'D', option_text: '가방이에요 (ga-bang-i-e-yo)' },
    { question_id: 271, option_key: 'A', option_text: '물 (mul)' },
    { question_id: 271, option_key: 'B', option_text: '옷 (ot)' },
    { question_id: 271, option_key: 'C', option_text: '밥 (bap)' },
    { question_id: 271, option_key: 'D', option_text: '가방 (ga-bang)' },
    { question_id: 272, option_key: 'A', option_text: '커피 (keo-pi)' },
    { question_id: 272, option_key: 'B', option_text: '식당 (sik-dang)' },
    { question_id: 272, option_key: 'C', option_text: '호텔 (ho-tel)' },
    { question_id: 272, option_key: 'D', option_text: '버스 (beo-seu)' },
    { question_id: 273, option_key: 'A', option_text: '카페 (ka-pe)' },
    { question_id: 273, option_key: 'B', option_text: '화장실 (hwa-jang-sil)' },
    { question_id: 273, option_key: 'C', option_text: '옷 (ot)' },
    { question_id: 273, option_key: 'D', option_text: '지하철 (ji-ha-cheol)' },
    { question_id: 274, option_key: 'A', option_text: '버스 (beo-seu)' },
    { question_id: 274, option_key: 'B', option_text: '호텔 (ho-tel)' },
    { question_id: 274, option_key: 'C', option_text: '가방 (ga-bang)' },
    { question_id: 274, option_key: 'D', option_text: '지하철 (ji-ha-cheol)' },
    { question_id: 275, option_key: 'A', option_text: '옷 (ot)' },
    { question_id: 275, option_key: 'B', option_text: '물 (mul)' },
    { question_id: 275, option_key: 'C', option_text: '밥 (bap)' },
    { question_id: 275, option_key: 'D', option_text: '카페 (ka-pe)' },
    { question_id: 276, option_key: 'A', option_text: '호텔 (ho-tel)' },
    { question_id: 276, option_key: 'B', option_text: '가방 (ga-bang)' },
    { question_id: 276, option_key: 'C', option_text: '식당 (sik-dang)' },
    { question_id: 276, option_key: 'D', option_text: '커피 (keo-pi)' },
    { question_id: 277, option_key: 'A', option_text: '화장실 (hwa-jang-sil)' },
    { question_id: 277, option_key: 'B', option_text: '버스 (beo-seu)' },
    { question_id: 277, option_key: 'C', option_text: '호텔 (ho-tel)' },
    { question_id: 277, option_key: 'D', option_text: '물 (mul)' },
    { question_id: 278, option_key: 'A', option_text: '지하철 (ji-ha-cheol)' },
    { question_id: 278, option_key: 'B', option_text: '밥 (bap)' },
    { question_id: 278, option_key: 'C', option_text: '카페 (ka-pe)' },
    { question_id: 278, option_key: 'D', option_text: '버스 (beo-seu)' },
    { question_id: 279, option_key: 'A', option_text: '식당 (sik-dang)' },
    { question_id: 279, option_key: 'B', option_text: '옷 (ot)' },
    { question_id: 279, option_key: 'C', option_text: '가방 (ga-bang)' },
    { question_id: 279, option_key: 'D', option_text: '지하철 (ji-ha-cheol)' },
    { question_id: 280, option_key: 'A', option_text: '커피 (keo-pi)' },
    { question_id: 280, option_key: 'B', option_text: '물 (mul)' },
    { question_id: 280, option_key: 'C', option_text: '호텔 (ho-tel)' },
    { question_id: 280, option_key: 'D', option_text: '버스 (beo-seu)' },
    { question_id: 281, option_key: 'A', option_text: 'kata sifat' },
    { question_id: 281, option_key: 'B', option_text: 'kata tempat' },
    { question_id: 281, option_key: 'C', option_text: 'kata benda' },
    { question_id: 281, option_key: 'D', option_text: 'kata sapaan' },
    { question_id: 282, option_key: 'A', option_text: 'Beli apa?' },
    { question_id: 282, option_key: 'B', option_text: 'Minum apa?' },
    { question_id: 282, option_key: 'C', option_text: 'Pergi ke mana?' },
    { question_id: 282, option_key: 'D', option_text: 'Makan apa?' },
    { question_id: 283, option_key: 'A', option_text: '뭘 먹어요? (mwol meo-geo-yo?)' },
    { question_id: 283, option_key: 'B', option_text: '뭘 사요? (mwol sa-yo?)' },
    { question_id: 283, option_key: 'C', option_text: '우유를 마셔요 (u-yu-reul ma-syeo-yo)' },
    { question_id: 283, option_key: 'D', option_text: '바나나우유를 마셔요 (ba-na-na-u-yu-reul ma-syeo-yo)' },
    { question_id: 284, option_key: 'A', option_text: 'Minum apa?' },
    { question_id: 284, option_key: 'B', option_text: 'Beli apa?' },
    { question_id: 284, option_key: 'C', option_text: 'Makan apa?' },
    { question_id: 284, option_key: 'D', option_text: 'Enak apa?' },
    { question_id: 285, option_key: 'A', option_text: '뭘 먹어요? (mwol meo-geo-yo?)' },
    { question_id: 285, option_key: 'B', option_text: '뭘 사요? (mwol sa-yo?)' },
    { question_id: 285, option_key: 'C', option_text: '우유를 마셔요 (u-yu-reul ma-syeo-yo)' },
    { question_id: 285, option_key: 'D', option_text: '밥을 먹어요 (ba-beul meo-geo-yo)' },
    { question_id: 286, option_key: 'A', option_text: 'membeli susu pisang' },
    { question_id: 286, option_key: 'B', option_text: 'makan susu pisang' },
    { question_id: 286, option_key: 'C', option_text: 'membeli kopi' },
    { question_id: 286, option_key: 'D', option_text: 'minum susu pisang' },
    { question_id: 287, option_key: 'A', option_text: '를 (reul)' },
    { question_id: 287, option_key: 'B', option_text: '우유 (u-yu)' },
    { question_id: 287, option_key: 'C', option_text: '마셔요 (ma-syeo-yo)' },
    { question_id: 287, option_key: 'D', option_text: '을 (eul)' },
    { question_id: 288, option_key: 'A', option_text: '을 (eul)' },
    { question_id: 288, option_key: 'B', option_text: '를 (reul)' },
    { question_id: 288, option_key: 'C', option_text: '에 (e)' },
    { question_id: 288, option_key: 'D', option_text: '은 (eun)' },
    { question_id: 289, option_key: 'A', option_text: '뭘 사요? → 뭘 먹어요?' },
    { question_id: 289, option_key: 'B', option_text: '우유를 마셔요 → 뭘 사요?' },
    { question_id: 289, option_key: 'C', option_text: '뭘 먹어요? → 밥을 먹어요' },
    { question_id: 289, option_key: 'D', option_text: '맛있어요 → 우유를 마셔요' },
    { question_id: 290, option_key: 'A', option_text: '뭘 먹어요? (mwol meo-geo-yo?)' },
    { question_id: 290, option_key: 'B', option_text: '우유를 마셔요 (u-yu-reul ma-syeo-yo)' },
    { question_id: 290, option_key: 'C', option_text: '밥을 먹어요 (ba-beul meo-geo-yo)' },
    { question_id: 290, option_key: 'D', option_text: '바나나우유를 마셔요 (ba-na-na-u-yu-reul ma-syeo-yo)' },
    { question_id: 291, option_key: 'A', option_text: '비싸요 (bi-ssa-yo)' },
    { question_id: 291, option_key: 'B', option_text: '맛있어요 (ma-si-sseo-yo)' },
    { question_id: 291, option_key: 'C', option_text: '싸요 (ssa-yo)' },
    { question_id: 291, option_key: 'D', option_text: '깨끗해요 (kkae-kkeut-hae-yo)' },
    { question_id: 292, option_key: 'A', option_text: 'enak' },
    { question_id: 292, option_key: 'B', option_text: 'bersih' },
    { question_id: 292, option_key: 'C', option_text: 'mahal' },
    { question_id: 292, option_key: 'D', option_text: 'dekat' },
    { question_id: 293, option_key: 'A', option_text: '싸요 (ssa-yo)' },
    { question_id: 293, option_key: 'B', option_text: '멀어요 (meo-reo-yo)' },
    { question_id: 293, option_key: 'C', option_text: '맛있어요 (ma-si-sseo-yo)' },
    { question_id: 293, option_key: 'D', option_text: '가까워요 (ga-kka-wo-yo)' },
    { question_id: 294, option_key: 'A', option_text: '비싸요 (bi-ssa-yo)' },
    { question_id: 294, option_key: 'B', option_text: '깨끗해요 (kkae-kkeut-hae-yo)' },
    { question_id: 294, option_key: 'C', option_text: '멀어요 (meo-reo-yo)' },
    { question_id: 294, option_key: 'D', option_text: '가까워요 (ga-kka-wo-yo)' },
    { question_id: 295, option_key: 'A', option_text: 'bersih' },
    { question_id: 295, option_key: 'B', option_text: 'jauh' },
    { question_id: 295, option_key: 'C', option_text: 'murah' },
    { question_id: 295, option_key: 'D', option_text: 'enak' },
    { question_id: 296, option_key: 'A', option_text: '깨끗해요 (kkae-kkeut-hae-yo)' },
    { question_id: 296, option_key: 'B', option_text: '비싸요 (bi-ssa-yo)' },
    { question_id: 296, option_key: 'C', option_text: '멀어요 (meo-reo-yo)' },
    { question_id: 296, option_key: 'D', option_text: '맛있어요 (ma-si-sseo-yo)' },
    { question_id: 297, option_key: 'A', option_text: '맛있어요 (ma-si-sseo-yo) dan 깨끗해요 (kkae-kkeut-hae-yo)' },
    { question_id: 297, option_key: 'B', option_text: '비싸요 (bi-ssa-yo) dan 싸요 (ssa-yo)' },
    { question_id: 297, option_key: 'C', option_text: '가까워요 (ga-kka-wo-yo) dan 싸요 (ssa-yo)' },
    { question_id: 297, option_key: 'D', option_text: '멀어요 (meo-reo-yo) dan 비싸요 (bi-ssa-yo)' },
    { question_id: 298, option_key: 'A', option_text: '맛있어요 (ma-si-sseo-yo)' },
    { question_id: 298, option_key: 'B', option_text: '가까워요 (ga-kka-wo-yo)' },
    { question_id: 298, option_key: 'C', option_text: '비싸요 (bi-ssa-yo)' },
    { question_id: 298, option_key: 'D', option_text: '깨끗해요 (kkae-kkeut-hae-yo)' },
    { question_id: 299, option_key: 'A', option_text: '멀어요 (meo-reo-yo)' },
    { question_id: 299, option_key: 'B', option_text: '싸요 (ssa-yo)' },
    { question_id: 299, option_key: 'C', option_text: '맛있어요 (ma-si-sseo-yo)' },
    { question_id: 299, option_key: 'D', option_text: '깨끗해요 (kkae-kkeut-hae-yo)' },
    { question_id: 300, option_key: 'A', option_text: '가까워요 (ga-kka-wo-yo)' },
    { question_id: 300, option_key: 'B', option_text: '비싸요 (bi-ssa-yo)' },
    { question_id: 300, option_key: 'C', option_text: '맛있어요 (ma-si-sseo-yo)' },
    { question_id: 300, option_key: 'D', option_text: '깨끗해요 (kkae-kkeut-hae-yo)' },
    { question_id: 301, option_key: 'A', option_text: '와요 (wa-yo)' },
    { question_id: 301, option_key: 'B', option_text: '가요 (ga-yo)' },
    { question_id: 301, option_key: 'C', option_text: '봐요 (bwa-yo)' },
    { question_id: 301, option_key: 'D', option_text: '먹어요 (meo-geo-yo)' },
    { question_id: 302, option_key: 'A', option_text: 'datang' },
    { question_id: 302, option_key: 'B', option_text: 'pergi' },
    { question_id: 302, option_key: 'C', option_text: 'makan' },
    { question_id: 302, option_key: 'D', option_text: 'beli' },
    { question_id: 303, option_key: 'A', option_text: '마셔요 (ma-syeo-yo)' },
    { question_id: 303, option_key: 'B', option_text: '사요 (sa-yo)' },
    { question_id: 303, option_key: 'C', option_text: '봐요 (bwa-yo)' },
    { question_id: 303, option_key: 'D', option_text: '가요 (ga-yo)' },
    { question_id: 304, option_key: 'A', option_text: 'minum' },
    { question_id: 304, option_key: 'B', option_text: 'datang' },
    { question_id: 304, option_key: 'C', option_text: 'beli' },
    { question_id: 304, option_key: 'D', option_text: 'makan' },
    { question_id: 305, option_key: 'A', option_text: '사요 (sa-yo)' },
    { question_id: 305, option_key: 'B', option_text: '봐요 (bwa-yo)' },
    { question_id: 305, option_key: 'C', option_text: '와요 (wa-yo)' },
    { question_id: 305, option_key: 'D', option_text: '마셔요 (ma-syeo-yo)' },
    { question_id: 306, option_key: 'A', option_text: 'pergi' },
    { question_id: 306, option_key: 'B', option_text: 'minum' },
    { question_id: 306, option_key: 'C', option_text: 'makan' },
    { question_id: 306, option_key: 'D', option_text: 'lihat/tonton' },
    { question_id: 307, option_key: 'A', option_text: '먹어요 (meo-geo-yo)' },
    { question_id: 307, option_key: 'B', option_text: '가요 (ga-yo)' },
    { question_id: 307, option_key: 'C', option_text: '와요 (wa-yo)' },
    { question_id: 307, option_key: 'D', option_text: '봐요 (bwa-yo)' },
    { question_id: 308, option_key: 'A', option_text: '봐요 (bwa-yo)' },
    { question_id: 308, option_key: 'B', option_text: '마셔요 (ma-syeo-yo)' },
    { question_id: 308, option_key: 'C', option_text: '사요 (sa-yo)' },
    { question_id: 308, option_key: 'D', option_text: '와요 (wa-yo)' },
    { question_id: 309, option_key: 'A', option_text: '가요 (ga-yo) = datang' },
    { question_id: 309, option_key: 'B', option_text: '와요 (wa-yo) = pergi' },
    { question_id: 309, option_key: 'C', option_text: '사요 (sa-yo) = makan' },
    { question_id: 309, option_key: 'D', option_text: '봐요 (bwa-yo) = lihat/tonton' },
    { question_id: 310, option_key: 'A', option_text: '먹어요 (meo-geo-yo) dan 마셔요 (ma-syeo-yo)' },
    { question_id: 310, option_key: 'B', option_text: '가요 (ga-yo) dan 와요 (wa-yo)' },
    { question_id: 310, option_key: 'C', option_text: '봐요 (bwa-yo) dan 사요 (sa-yo)' },
    { question_id: 310, option_key: 'D', option_text: '사요 (sa-yo) dan 와요 (wa-yo)' },
    { question_id: 311, option_key: 'A', option_text: 'subjek + kata benda' },
    { question_id: 311, option_key: 'B', option_text: 'subjek + kata kerja' },
    { question_id: 311, option_key: 'C', option_text: 'tempat + posisi' },
    { question_id: 311, option_key: 'D', option_text: 'angka + harga' },
    { question_id: 312, option_key: 'A', option_text: 'Saya membeli kopi' },
    { question_id: 312, option_key: 'B', option_text: 'Saya minum susu' },
    { question_id: 312, option_key: 'C', option_text: 'Saya makan nasi' },
    { question_id: 312, option_key: 'D', option_text: 'Saya pergi ke hotel' },
    { question_id: 313, option_key: 'A', option_text: '저는 커피를 마셔요 (jeo-neun keo-pi-reul ma-syeo-yo)' },
    { question_id: 313, option_key: 'B', option_text: '저는 밥을 먹어요 (jeo-neun ba-beul meo-geo-yo)' },
    { question_id: 313, option_key: 'C', option_text: '커피가 가까워요 (keo-pi-ga ga-kka-wo-yo)' },
    { question_id: 313, option_key: 'D', option_text: '가방이 비싸요 (ga-bang-i bi-ssa-yo)' },
    { question_id: 314, option_key: 'A', option_text: 'Saya membeli kopi' },
    { question_id: 314, option_key: 'B', option_text: 'Saya makan kopi' },
    { question_id: 314, option_key: 'C', option_text: 'Saya melihat kopi' },
    { question_id: 314, option_key: 'D', option_text: 'Saya minum kopi' },
    { question_id: 315, option_key: 'A', option_text: '저는 커피를 마셔요 (jeo-neun keo-pi-reul ma-syeo-yo)' },
    { question_id: 315, option_key: 'B', option_text: '저는 밥을 먹어요 (jeo-neun ba-beul meo-geo-yo)' },
    { question_id: 315, option_key: 'C', option_text: '커피가 가까워요 (keo-pi-ga ga-kka-wo-yo)' },
    { question_id: 315, option_key: 'D', option_text: '가방이 비싸요 (ga-bang-i bi-ssa-yo)' },
    { question_id: 316, option_key: 'A', option_text: 'benda memiliki sifat tertentu' },
    { question_id: 316, option_key: 'B', option_text: 'seseorang melakukan aktivitas' },
    { question_id: 316, option_key: 'C', option_text: 'harga benda' },
    { question_id: 316, option_key: 'D', option_text: 'angka Sino' },
    { question_id: 317, option_key: 'A', option_text: 'Tas dekat' },
    { question_id: 317, option_key: 'B', option_text: 'Tas mahal' },
    { question_id: 317, option_key: 'C', option_text: 'Tas bersih' },
    { question_id: 317, option_key: 'D', option_text: 'Tas murah' },
    { question_id: 318, option_key: 'A', option_text: '커피가 가까워요 (keo-pi-ga ga-kka-wo-yo)' },
    { question_id: 318, option_key: 'B', option_text: '저는 밥을 먹어요 (jeo-neun ba-beul meo-geo-yo)' },
    { question_id: 318, option_key: 'C', option_text: '가방이 비싸요 (ga-bang-i bi-ssa-yo)' },
    { question_id: 318, option_key: 'D', option_text: '저는 커피를 마셔요 (jeo-neun keo-pi-reul ma-syeo-yo)' },
    { question_id: 319, option_key: 'A', option_text: 'Kopi dekat' },
    { question_id: 319, option_key: 'B', option_text: 'Kopi mahal' },
    { question_id: 319, option_key: 'C', option_text: 'Saya minum kopi' },
    { question_id: 319, option_key: 'D', option_text: 'Saya membeli kopi' },
    { question_id: 320, option_key: 'A', option_text: '저는 밥을 먹어요 (jeo-neun ba-beul meo-geo-yo)' },
    { question_id: 320, option_key: 'B', option_text: '저는 커피를 마셔요 (jeo-neun keo-pi-reul ma-syeo-yo)' },
    { question_id: 320, option_key: 'C', option_text: '가요 (ga-yo)' },
    { question_id: 320, option_key: 'D', option_text: '가방이 비싸요 (ga-bang-i bi-ssa-yo)' },
    { question_id: 321, option_key: 'A', option_text: '일' },
    { question_id: 321, option_key: 'B', option_text: '삼' },
    { question_id: 321, option_key: 'C', option_text: '공/영' },
    { question_id: 321, option_key: 'D', option_text: '오' },
    { question_id: 322, option_key: 'A', option_text: '일' },
    { question_id: 322, option_key: 'B', option_text: '이' },
    { question_id: 322, option_key: 'C', option_text: '삼' },
    { question_id: 322, option_key: 'D', option_text: '사' },
    { question_id: 323, option_key: 'A', option_text: '2' },
    { question_id: 323, option_key: 'B', option_text: '3' },
    { question_id: 323, option_key: 'C', option_text: '4' },
    { question_id: 323, option_key: 'D', option_text: '5' },
    { question_id: 324, option_key: 'A', option_text: '사' },
    { question_id: 324, option_key: 'B', option_text: '오' },
    { question_id: 324, option_key: 'C', option_text: '육' },
    { question_id: 324, option_key: 'D', option_text: '칠' },
    { question_id: 325, option_key: 'A', option_text: '3' },
    { question_id: 325, option_key: 'B', option_text: '4' },
    { question_id: 325, option_key: 'C', option_text: '5' },
    { question_id: 325, option_key: 'D', option_text: '6' },
    { question_id: 326, option_key: 'A', option_text: '육' },
    { question_id: 326, option_key: 'B', option_text: '칠' },
    { question_id: 326, option_key: 'C', option_text: '팔' },
    { question_id: 326, option_key: 'D', option_text: '구' },
    { question_id: 327, option_key: 'A', option_text: '7' },
    { question_id: 327, option_key: 'B', option_text: '8' },
    { question_id: 327, option_key: 'C', option_text: '9' },
    { question_id: 327, option_key: 'D', option_text: '10' },
    { question_id: 328, option_key: 'A', option_text: '백' },
    { question_id: 328, option_key: 'B', option_text: '천' },
    { question_id: 328, option_key: 'C', option_text: '만' },
    { question_id: 328, option_key: 'D', option_text: '십' },
    { question_id: 329, option_key: 'A', option_text: '백 = 100' },
    { question_id: 329, option_key: 'B', option_text: '천 = 100' },
    { question_id: 329, option_key: 'C', option_text: '만 = 1000' },
    { question_id: 329, option_key: 'D', option_text: '십 = 10000' },
    { question_id: 330, option_key: 'A', option_text: 'Ini apa?' },
    { question_id: 330, option_key: 'B', option_text: 'Ini berapa harganya?' },
    { question_id: 330, option_key: 'C', option_text: 'Ini tas?' },
    { question_id: 330, option_key: 'D', option_text: 'Saya beli ini' }

  ];

  for (const opt of options) {
    await db.query(
      `
      INSERT INTO quiz_options (question_id, option_key, option_text) 
      VALUES (?, ?, ?)
      ON DUPLICATE KEY UPDATE 
        option_text = VALUES(option_text)
      `,
      [opt.question_id, opt.option_key, opt.option_text] 
    );
}

  console.log(`Berhasil memasukkan ${options.length} data ke quiz_options.`);

  return options;
}